/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/ra-144.
 *
 * RA 144 decoder, encoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_ra_144_decoder;
extern const struct FFCodec ff_ra_144_encoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_ra_144_codec_1(void)
{
	return &ff_ra_144_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_ra_144_codec_2(void)
{
	return &ff_ra_144_encoder;
}
