/*
 * Build-time shim for the adts-muxer extension.
 *
 * Forces the FFmpeg CONFIG_* flags this extension needs to 1
 * BEFORE the FFmpeg headers pull in config_components.h, so the
 * relevant decode/encode/demux/mux code paths aren't DCE'd by
 * the C preprocessor.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand.
 */
#ifndef TTN_EXT_ADTS_MUXER_SHIM_H
#define TTN_EXT_ADTS_MUXER_SHIM_H

#define CONFIG_ADTS_MUXER 1
#define CONFIG_MPEG4AUDIO 1

#endif
