/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/image2pipe-demuxer.
 *
 * IMAGE2PIPE demuxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_image2pipe_demuxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_image2pipe_demuxer_demuxer_1(void)
{
	return &ff_image2pipe_demuxer;
}
