/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/yop.
 *
 * YOP decoder, demuxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_yop_decoder;
extern const struct AVInputFormat ff_yop_demuxer;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_yop_codec_1(void)
{
	return &ff_yop_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_yop_demuxer_1(void)
{
	return &ff_yop_demuxer;
}
