/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/h264-demuxer.
 *
 * H264 demuxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_h264_demuxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_h264_demuxer_demuxer_1(void)
{
	return &ff_h264_demuxer;
}
