/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/g723-1-decoder.
 *
 * G723 1 decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_g723_1_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_g723_1_decoder_codec_1(void)
{
	return &ff_g723_1_decoder;
}
