/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/codec2.
 *
 * CODEC2 demuxer, muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_codec2_demuxer;
extern const struct AVOutputFormat ff_codec2_muxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_codec2_demuxer_1(void)
{
	return &ff_codec2_demuxer;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_codec2_muxer_1(void)
{
	return &ff_codec2_muxer;
}
