/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/spdif.
 *
 * SPDIF demuxer, muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_spdif_demuxer;
extern const struct AVOutputFormat ff_spdif_muxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_spdif_demuxer_1(void)
{
	return &ff_spdif_demuxer;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_spdif_muxer_1(void)
{
	return &ff_spdif_muxer;
}
