/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/g7xx.
 *
 * G7XX family (2 decoders, 1 encoder, 5 demuxers, 4 muxers).
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_g722_demuxer;
extern const struct AVOutputFormat ff_g722_muxer;
extern const struct FFCodec ff_g723_1_decoder;
extern const struct AVInputFormat ff_g723_1_demuxer;
extern const struct FFCodec ff_g723_1_encoder;
extern const struct AVOutputFormat ff_g723_1_muxer;
extern const struct AVInputFormat ff_g726_demuxer;
extern const struct AVOutputFormat ff_g726_muxer;
extern const struct AVInputFormat ff_g726le_demuxer;
extern const struct AVOutputFormat ff_g726le_muxer;
extern const struct FFCodec ff_g729_decoder;
extern const struct AVInputFormat ff_g729_demuxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_g7xx_demuxer_1(void)
{
	return &ff_g722_demuxer;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_g7xx_muxer_1(void)
{
	return &ff_g722_muxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_g7xx_codec_1(void)
{
	return &ff_g723_1_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_g7xx_demuxer_2(void)
{
	return &ff_g723_1_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_g7xx_codec_2(void)
{
	return &ff_g723_1_encoder;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_g7xx_muxer_2(void)
{
	return &ff_g723_1_muxer;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_g7xx_demuxer_3(void)
{
	return &ff_g726_demuxer;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_g7xx_muxer_3(void)
{
	return &ff_g726_muxer;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_g7xx_demuxer_4(void)
{
	return &ff_g726le_demuxer;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_g7xx_muxer_4(void)
{
	return &ff_g726le_muxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_g7xx_codec_3(void)
{
	return &ff_g729_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_g7xx_demuxer_5(void)
{
	return &ff_g729_demuxer;
}
