/*
 * Build-time shim for the g7xx extension.
 *
 * `-include`d before any FFmpeg source compiles. We:
 *
 *   1. Pull in upstream's `config.h` + `config_components.h`
 *      so all the HAVE_X / ARCH_X / CONFIG_X defines exist.
 *
 *   2. `#undef` + `#define CONFIG_X 1` for every flag this
 *      extension needs active. C preprocessing rule: last
 *      define wins, so our overrides take effect for all
 *      subsequent source compiles.
 *
 * Without step 2, FFmpeg's per-codec source files DCE their
 * own decode/encode paths because the base build set every
 * `CONFIG_X` to 0.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand.
 */
#ifndef TTN_EXT_G7XX_SHIM_H
#define TTN_EXT_G7XX_SHIM_H

#include "config.h"
#include "config_components.h"

#undef CONFIG_G722_DEMUXER
#define CONFIG_G722_DEMUXER 1
#undef CONFIG_G722_MUXER
#define CONFIG_G722_MUXER 1
#undef CONFIG_G723_1_DECODER
#define CONFIG_G723_1_DECODER 1
#undef CONFIG_G723_1_DEMUXER
#define CONFIG_G723_1_DEMUXER 1
#undef CONFIG_G723_1_ENCODER
#define CONFIG_G723_1_ENCODER 1
#undef CONFIG_G723_1_MUXER
#define CONFIG_G723_1_MUXER 1
#undef CONFIG_G726LE_DEMUXER
#define CONFIG_G726LE_DEMUXER 1
#undef CONFIG_G726LE_MUXER
#define CONFIG_G726LE_MUXER 1
#undef CONFIG_G726_DEMUXER
#define CONFIG_G726_DEMUXER 1
#undef CONFIG_G726_MUXER
#define CONFIG_G726_MUXER 1
#undef CONFIG_G729_DECODER
#define CONFIG_G729_DECODER 1
#undef CONFIG_G729_DEMUXER
#define CONFIG_G729_DEMUXER 1

#endif
