/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/rv10-encoder.
 *
 * RV10 encoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_rv10_encoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_rv10_encoder_codec_1(void)
{
	return &ff_rv10_encoder;
}
