/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/adpcm-sbpro-2-decoder.
 *
 * ADPCM SBPRO 2 decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_adpcm_sbpro_2_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_sbpro_2_decoder_codec_1(void)
{
	return &ff_adpcm_sbpro_2_decoder;
}
