/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/flv.
 *
 * FLV decoder, encoder, demuxer, muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_flv_decoder;
extern const struct AVInputFormat ff_flv_demuxer;
extern const struct FFCodec ff_flv_encoder;
extern const struct AVOutputFormat ff_flv_muxer;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_flv_codec_1(void)
{
	return &ff_flv_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_flv_demuxer_1(void)
{
	return &ff_flv_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_flv_codec_2(void)
{
	return &ff_flv_encoder;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_flv_muxer_1(void)
{
	return &ff_flv_muxer;
}
