/*
 * Build-time shim for the mpegts-muxer extension.
 *
 * `-include`d before any FFmpeg source compiles. We:
 *
 *   1. Pull in upstream's `config.h` + `config_components.h`
 *      so all the HAVE_X / ARCH_X / CONFIG_X defines exist.
 *
 *   2. `#undef` + `#define CONFIG_X 1` for every flag this
 *      extension needs active. C preprocessing rule: last
 *      define wins, so our overrides take effect for all
 *      subsequent source compiles.
 *
 * Without step 2, FFmpeg's per-codec source files DCE their
 * own decode/encode paths because the base build set every
 * `CONFIG_X` to 0.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand.
 */
#ifndef TTN_EXT_MPEGTS_MUXER_SHIM_H
#define TTN_EXT_MPEGTS_MUXER_SHIM_H

#include "config.h"
#include "config_components.h"

#undef CONFIG_AAC_ADTSTOASC_BSF
#define CONFIG_AAC_ADTSTOASC_BSF 1
#undef CONFIG_AC3_PARSER
#define CONFIG_AC3_PARSER 1
#undef CONFIG_ADTS_HEADER
#define CONFIG_ADTS_HEADER 1
#undef CONFIG_ADTS_MUXER
#define CONFIG_ADTS_MUXER 1
#undef CONFIG_H264_MP4TOANNEXB_BSF
#define CONFIG_H264_MP4TOANNEXB_BSF 1
#undef CONFIG_HEVC_MP4TOANNEXB_BSF
#define CONFIG_HEVC_MP4TOANNEXB_BSF 1
#undef CONFIG_LATM_MUXER
#define CONFIG_LATM_MUXER 1
#undef CONFIG_MPEGTS_MUXER
#define CONFIG_MPEGTS_MUXER 1

#endif
