/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/pcm-s64le-encoder.
 *
 * PCM S64LE encoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_pcm_s64le_encoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_s64le_encoder_codec_1(void)
{
	return &ff_pcm_s64le_encoder;
}
