/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/wmv.
 *
 * WMV family (10 decoders, 4 encoders, 5 demuxers, 3 muxers).
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_asf_demuxer;
extern const struct AVOutputFormat ff_asf_muxer;
extern const struct AVInputFormat ff_asf_o_demuxer;
extern const struct FFCodec ff_vc1_decoder;
extern const struct AVInputFormat ff_vc1_demuxer;
extern const struct AVOutputFormat ff_vc1_muxer;
extern const struct AVInputFormat ff_vc1t_demuxer;
extern const struct AVOutputFormat ff_vc1t_muxer;
extern const struct FFCodec ff_wmalossless_decoder;
extern const struct FFCodec ff_wmapro_decoder;
extern const struct FFCodec ff_wmav1_decoder;
extern const struct FFCodec ff_wmav1_encoder;
extern const struct FFCodec ff_wmav2_decoder;
extern const struct FFCodec ff_wmav2_encoder;
extern const struct FFCodec ff_wmavoice_decoder;
extern const struct FFCodec ff_wmv1_decoder;
extern const struct FFCodec ff_wmv1_encoder;
extern const struct FFCodec ff_wmv2_decoder;
extern const struct FFCodec ff_wmv2_encoder;
extern const struct FFCodec ff_xma1_decoder;
extern const struct FFCodec ff_xma2_decoder;
extern const struct AVInputFormat ff_xwma_demuxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_wmv_demuxer_1(void)
{
	return &ff_asf_demuxer;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_wmv_muxer_1(void)
{
	return &ff_asf_muxer;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_wmv_demuxer_2(void)
{
	return &ff_asf_o_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_wmv_codec_1(void)
{
	return &ff_vc1_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_wmv_demuxer_3(void)
{
	return &ff_vc1_demuxer;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_wmv_muxer_2(void)
{
	return &ff_vc1_muxer;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_wmv_demuxer_4(void)
{
	return &ff_vc1t_demuxer;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_wmv_muxer_3(void)
{
	return &ff_vc1t_muxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_wmv_codec_2(void)
{
	return &ff_wmalossless_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_wmv_codec_3(void)
{
	return &ff_wmapro_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_wmv_codec_4(void)
{
	return &ff_wmav1_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_wmv_codec_5(void)
{
	return &ff_wmav1_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_wmv_codec_6(void)
{
	return &ff_wmav2_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_wmv_codec_7(void)
{
	return &ff_wmav2_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_wmv_codec_8(void)
{
	return &ff_wmavoice_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_wmv_codec_9(void)
{
	return &ff_wmv1_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_wmv_codec_10(void)
{
	return &ff_wmv1_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_wmv_codec_11(void)
{
	return &ff_wmv2_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_wmv_codec_12(void)
{
	return &ff_wmv2_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_wmv_codec_13(void)
{
	return &ff_xma1_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_wmv_codec_14(void)
{
	return &ff_xma2_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_wmv_demuxer_5(void)
{
	return &ff_xwma_demuxer;
}
