/*
 * Build-time shim for the wmv extension.
 *
 * `-include`d before any FFmpeg source compiles. We:
 *
 *   1. Pull in upstream's `config.h` + `config_components.h`
 *      so all the HAVE_X / ARCH_X / CONFIG_X defines exist.
 *
 *   2. `#undef` + `#define CONFIG_X 1` for every flag this
 *      extension needs active. C preprocessing rule: last
 *      define wins, so our overrides take effect for all
 *      subsequent source compiles.
 *
 * Without step 2, FFmpeg's per-codec source files DCE their
 * own decode/encode paths because the base build set every
 * `CONFIG_X` to 0.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand.
 */
#ifndef TTN_EXT_WMV_SHIM_H
#define TTN_EXT_WMV_SHIM_H

#include "config.h"
#include "config_components.h"

#undef CONFIG_ASF_DEMUXER
#define CONFIG_ASF_DEMUXER 1
#undef CONFIG_ASF_MUXER
#define CONFIG_ASF_MUXER 1
#undef CONFIG_ASF_O_DEMUXER
#define CONFIG_ASF_O_DEMUXER 1
#undef CONFIG_H263DSP
#define CONFIG_H263DSP 1
#undef CONFIG_H263_DECODER
#define CONFIG_H263_DECODER 1
#undef CONFIG_H263_ENCODER
#define CONFIG_H263_ENCODER 1
#undef CONFIG_H263_PARSER
#define CONFIG_H263_PARSER 1
#undef CONFIG_LLAUDDSP
#define CONFIG_LLAUDDSP 1
#undef CONFIG_LSP
#define CONFIG_LSP 1
#undef CONFIG_RIFFDEC
#define CONFIG_RIFFDEC 1
#undef CONFIG_RIFFENC
#define CONFIG_RIFFENC 1
#undef CONFIG_STARTCODE
#define CONFIG_STARTCODE 1
#undef CONFIG_VC1DSP
#define CONFIG_VC1DSP 1
#undef CONFIG_VC1T_DEMUXER
#define CONFIG_VC1T_DEMUXER 1
#undef CONFIG_VC1T_MUXER
#define CONFIG_VC1T_MUXER 1
#undef CONFIG_VC1_DECODER
#define CONFIG_VC1_DECODER 1
#undef CONFIG_VC1_DEMUXER
#define CONFIG_VC1_DEMUXER 1
#undef CONFIG_VC1_MUXER
#define CONFIG_VC1_MUXER 1
#undef CONFIG_WMALOSSLESS_DECODER
#define CONFIG_WMALOSSLESS_DECODER 1
#undef CONFIG_WMAPRO_DECODER
#define CONFIG_WMAPRO_DECODER 1
#undef CONFIG_WMAV1_DECODER
#define CONFIG_WMAV1_DECODER 1
#undef CONFIG_WMAV1_ENCODER
#define CONFIG_WMAV1_ENCODER 1
#undef CONFIG_WMAV2_DECODER
#define CONFIG_WMAV2_DECODER 1
#undef CONFIG_WMAV2_ENCODER
#define CONFIG_WMAV2_ENCODER 1
#undef CONFIG_WMAVOICE_DECODER
#define CONFIG_WMAVOICE_DECODER 1
#undef CONFIG_WMV1_DECODER
#define CONFIG_WMV1_DECODER 1
#undef CONFIG_WMV1_ENCODER
#define CONFIG_WMV1_ENCODER 1
#undef CONFIG_WMV2_DECODER
#define CONFIG_WMV2_DECODER 1
#undef CONFIG_WMV2_ENCODER
#define CONFIG_WMV2_ENCODER 1
#undef CONFIG_XMA1_DECODER
#define CONFIG_XMA1_DECODER 1
#undef CONFIG_XMA2_DECODER
#define CONFIG_XMA2_DECODER 1
#undef CONFIG_XWMA_DEMUXER
#define CONFIG_XWMA_DEMUXER 1

#endif
