/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/alac.
 *
 * ALAC decoder, encoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_alac_decoder;
extern const struct FFCodec ff_alac_encoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_alac_codec_1(void)
{
	return &ff_alac_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_alac_codec_2(void)
{
	return &ff_alac_encoder;
}
