/*
 * Build-time shim for the matroska extension.
 *
 * `-include`d before any FFmpeg source compiles. We:
 *
 *   1. Pull in upstream's `config.h` + `config_components.h`
 *      so all the HAVE_X / ARCH_X / CONFIG_X defines exist.
 *
 *   2. `#undef` + `#define CONFIG_X 1` for every flag this
 *      extension needs active. C preprocessing rule: last
 *      define wins, so our overrides take effect for all
 *      subsequent source compiles.
 *
 * Without step 2, FFmpeg's per-codec source files DCE their
 * own decode/encode paths because the base build set every
 * `CONFIG_X` to 0.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand.
 */
#ifndef TTN_EXT_MATROSKA_SHIM_H
#define TTN_EXT_MATROSKA_SHIM_H

#include "config.h"
#include "config_components.h"

#undef CONFIG_AAC_ADTSTOASC_BSF
#define CONFIG_AAC_ADTSTOASC_BSF 1
#undef CONFIG_ADTS_HEADER
#define CONFIG_ADTS_HEADER 1
#undef CONFIG_MATROSKA_DEMUXER
#define CONFIG_MATROSKA_DEMUXER 1
#undef CONFIG_MATROSKA_MUXER
#define CONFIG_MATROSKA_MUXER 1
#undef CONFIG_PGS_FRAME_MERGE_BSF
#define CONFIG_PGS_FRAME_MERGE_BSF 1
#undef CONFIG_RIFFDEC
#define CONFIG_RIFFDEC 1
#undef CONFIG_RIFFENC
#define CONFIG_RIFFENC 1
#undef CONFIG_VP9_SUPERFRAME_BSF
#define CONFIG_VP9_SUPERFRAME_BSF 1

#endif
