/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/sonic-encoder.
 *
 * SONIC encoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_sonic_encoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_sonic_encoder_codec_1(void)
{
	return &ff_sonic_encoder;
}
