/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/sdx2-dpcm-decoder.
 *
 * SDX2 DPCM decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_sdx2_dpcm_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_sdx2_dpcm_decoder_codec_1(void)
{
	return &ff_sdx2_dpcm_decoder;
}
