/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/mxf.
 *
 * MXF demuxer, muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_mxf_demuxer;
extern const struct AVOutputFormat ff_mxf_muxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_mxf_demuxer_1(void)
{
	return &ff_mxf_demuxer;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_mxf_muxer_1(void)
{
	return &ff_mxf_muxer;
}
