/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/nut.
 *
 * NUT demuxer, muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_nut_demuxer;
extern const struct AVOutputFormat ff_nut_muxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_nut_demuxer_1(void)
{
	return &ff_nut_demuxer;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_nut_muxer_1(void)
{
	return &ff_nut_muxer;
}
