/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/yuv4mpegpipe.
 *
 * YUV4MPEGPIPE demuxer, muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_yuv4mpegpipe_demuxer;
extern const struct AVOutputFormat ff_yuv4mpegpipe_muxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_yuv4mpegpipe_demuxer_1(void)
{
	return &ff_yuv4mpegpipe_demuxer;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_yuv4mpegpipe_muxer_1(void)
{
	return &ff_yuv4mpegpipe_muxer;
}
