/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/pcm-s16be-demuxer.
 *
 * PCM S16BE demuxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_pcm_s16be_demuxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_pcm_s16be_demuxer_demuxer_1(void)
{
	return &ff_pcm_s16be_demuxer;
}
