/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/argo-asf.
 *
 * ARGO ASF demuxer, muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_argo_asf_demuxer;
extern const struct AVOutputFormat ff_argo_asf_muxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_argo_asf_demuxer_1(void)
{
	return &ff_argo_asf_demuxer;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_argo_asf_muxer_1(void)
{
	return &ff_argo_asf_muxer;
}
