/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/mvi-demuxer.
 *
 * MVI demuxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_mvi_demuxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_mvi_demuxer_demuxer_1(void)
{
	return &ff_mvi_demuxer;
}
