/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/adpcm-agm-decoder.
 *
 * ADPCM AGM decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_adpcm_agm_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_agm_decoder_codec_1(void)
{
	return &ff_adpcm_agm_decoder;
}
