/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/mp3-demuxer.
 *
 * MP3 demuxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_mp3_demuxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_mp3_demuxer_demuxer_1(void)
{
	return &ff_mp3_demuxer;
}
