/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/ffmetadata.
 *
 * FFMETADATA demuxer, muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_ffmetadata_demuxer;
extern const struct AVOutputFormat ff_ffmetadata_muxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_ffmetadata_demuxer_1(void)
{
	return &ff_ffmetadata_demuxer;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_ffmetadata_muxer_1(void)
{
	return &ff_ffmetadata_muxer;
}
