/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/ilbc.
 *
 * ILBC decoder, demuxer, muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_ilbc_decoder;
extern const struct AVInputFormat ff_ilbc_demuxer;
extern const struct AVOutputFormat ff_ilbc_muxer;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_ilbc_codec_1(void)
{
	return &ff_ilbc_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_ilbc_demuxer_1(void)
{
	return &ff_ilbc_demuxer;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_ilbc_muxer_1(void)
{
	return &ff_ilbc_muxer;
}
