/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/dpx-encoder.
 *
 * DPX encoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_dpx_encoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_dpx_encoder_codec_1(void)
{
	return &ff_dpx_encoder;
}
