/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/mp2-muxer.
 *
 * MP2 muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVOutputFormat ff_mp2_muxer;

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_mp2_muxer_muxer_1(void)
{
	return &ff_mp2_muxer;
}
