/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/mlp-encoder.
 *
 * MLP encoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_mlp_encoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_mlp_encoder_codec_1(void)
{
	return &ff_mlp_encoder;
}
