/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/cljr.
 *
 * CLJR decoder, encoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_cljr_decoder;
extern const struct FFCodec ff_cljr_encoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_cljr_codec_1(void)
{
	return &ff_cljr_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_cljr_codec_2(void)
{
	return &ff_cljr_encoder;
}
