/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/adpcm.
 *
 * ADPCM family (51 decoders, 15 encoders).
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_adpcm_4xm_decoder;
extern const struct FFCodec ff_adpcm_adx_decoder;
extern const struct FFCodec ff_adpcm_adx_encoder;
extern const struct FFCodec ff_adpcm_afc_decoder;
extern const struct FFCodec ff_adpcm_agm_decoder;
extern const struct FFCodec ff_adpcm_aica_decoder;
extern const struct FFCodec ff_adpcm_argo_decoder;
extern const struct FFCodec ff_adpcm_argo_encoder;
extern const struct FFCodec ff_adpcm_ct_decoder;
extern const struct FFCodec ff_adpcm_dtk_decoder;
extern const struct FFCodec ff_adpcm_ea_decoder;
extern const struct FFCodec ff_adpcm_ea_maxis_xa_decoder;
extern const struct FFCodec ff_adpcm_ea_r1_decoder;
extern const struct FFCodec ff_adpcm_ea_r2_decoder;
extern const struct FFCodec ff_adpcm_ea_r3_decoder;
extern const struct FFCodec ff_adpcm_ea_xas_decoder;
extern const struct FFCodec ff_adpcm_g722_decoder;
extern const struct FFCodec ff_adpcm_g722_encoder;
extern const struct FFCodec ff_adpcm_g726_decoder;
extern const struct FFCodec ff_adpcm_g726_encoder;
extern const struct FFCodec ff_adpcm_g726le_decoder;
extern const struct FFCodec ff_adpcm_g726le_encoder;
extern const struct FFCodec ff_adpcm_ima_acorn_decoder;
extern const struct FFCodec ff_adpcm_ima_alp_decoder;
extern const struct FFCodec ff_adpcm_ima_alp_encoder;
extern const struct FFCodec ff_adpcm_ima_amv_decoder;
extern const struct FFCodec ff_adpcm_ima_amv_encoder;
extern const struct FFCodec ff_adpcm_ima_apc_decoder;
extern const struct FFCodec ff_adpcm_ima_apm_decoder;
extern const struct FFCodec ff_adpcm_ima_apm_encoder;
extern const struct FFCodec ff_adpcm_ima_cunning_decoder;
extern const struct FFCodec ff_adpcm_ima_dat4_decoder;
extern const struct FFCodec ff_adpcm_ima_dk3_decoder;
extern const struct FFCodec ff_adpcm_ima_dk4_decoder;
extern const struct FFCodec ff_adpcm_ima_ea_eacs_decoder;
extern const struct FFCodec ff_adpcm_ima_ea_sead_decoder;
extern const struct FFCodec ff_adpcm_ima_iss_decoder;
extern const struct FFCodec ff_adpcm_ima_moflex_decoder;
extern const struct FFCodec ff_adpcm_ima_mtf_decoder;
extern const struct FFCodec ff_adpcm_ima_oki_decoder;
extern const struct FFCodec ff_adpcm_ima_qt_decoder;
extern const struct FFCodec ff_adpcm_ima_qt_encoder;
extern const struct FFCodec ff_adpcm_ima_rad_decoder;
extern const struct FFCodec ff_adpcm_ima_smjpeg_decoder;
extern const struct FFCodec ff_adpcm_ima_ssi_decoder;
extern const struct FFCodec ff_adpcm_ima_ssi_encoder;
extern const struct FFCodec ff_adpcm_ima_wav_decoder;
extern const struct FFCodec ff_adpcm_ima_wav_encoder;
extern const struct FFCodec ff_adpcm_ima_ws_decoder;
extern const struct FFCodec ff_adpcm_ima_ws_encoder;
extern const struct FFCodec ff_adpcm_ms_decoder;
extern const struct FFCodec ff_adpcm_ms_encoder;
extern const struct FFCodec ff_adpcm_mtaf_decoder;
extern const struct FFCodec ff_adpcm_psx_decoder;
extern const struct FFCodec ff_adpcm_sbpro_2_decoder;
extern const struct FFCodec ff_adpcm_sbpro_3_decoder;
extern const struct FFCodec ff_adpcm_sbpro_4_decoder;
extern const struct FFCodec ff_adpcm_swf_decoder;
extern const struct FFCodec ff_adpcm_swf_encoder;
extern const struct FFCodec ff_adpcm_thp_decoder;
extern const struct FFCodec ff_adpcm_thp_le_decoder;
extern const struct FFCodec ff_adpcm_vima_decoder;
extern const struct FFCodec ff_adpcm_xa_decoder;
extern const struct FFCodec ff_adpcm_yamaha_decoder;
extern const struct FFCodec ff_adpcm_yamaha_encoder;
extern const struct FFCodec ff_adpcm_zork_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_1(void)
{
	return &ff_adpcm_4xm_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_2(void)
{
	return &ff_adpcm_adx_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_3(void)
{
	return &ff_adpcm_adx_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_4(void)
{
	return &ff_adpcm_afc_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_5(void)
{
	return &ff_adpcm_agm_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_6(void)
{
	return &ff_adpcm_aica_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_7(void)
{
	return &ff_adpcm_argo_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_8(void)
{
	return &ff_adpcm_argo_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_9(void)
{
	return &ff_adpcm_ct_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_10(void)
{
	return &ff_adpcm_dtk_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_11(void)
{
	return &ff_adpcm_ea_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_12(void)
{
	return &ff_adpcm_ea_maxis_xa_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_13(void)
{
	return &ff_adpcm_ea_r1_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_14(void)
{
	return &ff_adpcm_ea_r2_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_15(void)
{
	return &ff_adpcm_ea_r3_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_16(void)
{
	return &ff_adpcm_ea_xas_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_17(void)
{
	return &ff_adpcm_g722_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_18(void)
{
	return &ff_adpcm_g722_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_19(void)
{
	return &ff_adpcm_g726_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_20(void)
{
	return &ff_adpcm_g726_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_21(void)
{
	return &ff_adpcm_g726le_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_22(void)
{
	return &ff_adpcm_g726le_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_23(void)
{
	return &ff_adpcm_ima_acorn_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_24(void)
{
	return &ff_adpcm_ima_alp_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_25(void)
{
	return &ff_adpcm_ima_alp_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_26(void)
{
	return &ff_adpcm_ima_amv_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_27(void)
{
	return &ff_adpcm_ima_amv_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_28(void)
{
	return &ff_adpcm_ima_apc_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_29(void)
{
	return &ff_adpcm_ima_apm_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_30(void)
{
	return &ff_adpcm_ima_apm_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_31(void)
{
	return &ff_adpcm_ima_cunning_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_32(void)
{
	return &ff_adpcm_ima_dat4_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_33(void)
{
	return &ff_adpcm_ima_dk3_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_34(void)
{
	return &ff_adpcm_ima_dk4_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_35(void)
{
	return &ff_adpcm_ima_ea_eacs_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_36(void)
{
	return &ff_adpcm_ima_ea_sead_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_37(void)
{
	return &ff_adpcm_ima_iss_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_38(void)
{
	return &ff_adpcm_ima_moflex_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_39(void)
{
	return &ff_adpcm_ima_mtf_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_40(void)
{
	return &ff_adpcm_ima_oki_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_41(void)
{
	return &ff_adpcm_ima_qt_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_42(void)
{
	return &ff_adpcm_ima_qt_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_43(void)
{
	return &ff_adpcm_ima_rad_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_44(void)
{
	return &ff_adpcm_ima_smjpeg_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_45(void)
{
	return &ff_adpcm_ima_ssi_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_46(void)
{
	return &ff_adpcm_ima_ssi_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_47(void)
{
	return &ff_adpcm_ima_wav_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_48(void)
{
	return &ff_adpcm_ima_wav_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_49(void)
{
	return &ff_adpcm_ima_ws_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_50(void)
{
	return &ff_adpcm_ima_ws_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_51(void)
{
	return &ff_adpcm_ms_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_52(void)
{
	return &ff_adpcm_ms_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_53(void)
{
	return &ff_adpcm_mtaf_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_54(void)
{
	return &ff_adpcm_psx_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_55(void)
{
	return &ff_adpcm_sbpro_2_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_56(void)
{
	return &ff_adpcm_sbpro_3_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_57(void)
{
	return &ff_adpcm_sbpro_4_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_58(void)
{
	return &ff_adpcm_swf_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_59(void)
{
	return &ff_adpcm_swf_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_60(void)
{
	return &ff_adpcm_thp_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_61(void)
{
	return &ff_adpcm_thp_le_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_62(void)
{
	return &ff_adpcm_vima_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_63(void)
{
	return &ff_adpcm_xa_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_64(void)
{
	return &ff_adpcm_yamaha_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_65(void)
{
	return &ff_adpcm_yamaha_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_codec_66(void)
{
	return &ff_adpcm_zork_decoder;
}
