/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/c93-decoder.
 *
 * C93 decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_c93_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_c93_decoder_codec_1(void)
{
	return &ff_c93_decoder;
}
