/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/rpza-encoder.
 *
 * RPZA encoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_rpza_encoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_rpza_encoder_codec_1(void)
{
	return &ff_rpza_encoder;
}
