/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/ws-snd1.
 *
 * WS SND1 decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_ws_snd1_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_ws_snd1_codec_1(void)
{
	return &ff_ws_snd1_decoder;
}
