/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/paf-audio-decoder.
 *
 * PAF AUDIO decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_paf_audio_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_paf_audio_decoder_codec_1(void)
{
	return &ff_paf_audio_decoder;
}
