/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/aptx-hd.
 *
 * APTX HD decoder, encoder, demuxer, muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_aptx_hd_decoder;
extern const struct AVInputFormat ff_aptx_hd_demuxer;
extern const struct FFCodec ff_aptx_hd_encoder;
extern const struct AVOutputFormat ff_aptx_hd_muxer;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_aptx_hd_codec_1(void)
{
	return &ff_aptx_hd_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_aptx_hd_demuxer_1(void)
{
	return &ff_aptx_hd_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_aptx_hd_codec_2(void)
{
	return &ff_aptx_hd_encoder;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_aptx_hd_muxer_1(void)
{
	return &ff_aptx_hd_muxer;
}
