/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/apm-demuxer.
 *
 * APM demuxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_apm_demuxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_apm_demuxer_demuxer_1(void)
{
	return &ff_apm_demuxer;
}
