/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/jpeg2000-encoder.
 *
 * JPEG2000 encoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_jpeg2000_encoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_jpeg2000_encoder_codec_1(void)
{
	return &ff_jpeg2000_encoder;
}
