/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/h261-demuxer.
 *
 * H261 demuxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_h261_demuxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_h261_demuxer_demuxer_1(void)
{
	return &ff_h261_demuxer;
}
