/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/webm-dash-manifest-muxer.
 *
 * WEBM DASH MANIFEST muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVOutputFormat ff_webm_dash_manifest_muxer;

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_webm_dash_manifest_muxer_muxer_1(void)
{
	return &ff_webm_dash_manifest_muxer;
}
