/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/sbc.
 *
 * SBC decoder, encoder, demuxer, muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_sbc_decoder;
extern const struct AVInputFormat ff_sbc_demuxer;
extern const struct FFCodec ff_sbc_encoder;
extern const struct AVOutputFormat ff_sbc_muxer;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_sbc_codec_1(void)
{
	return &ff_sbc_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_sbc_demuxer_1(void)
{
	return &ff_sbc_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_sbc_codec_2(void)
{
	return &ff_sbc_encoder;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_sbc_muxer_1(void)
{
	return &ff_sbc_muxer;
}
