/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/mpeg2dvd.
 *
 * MPEG2DVD muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVOutputFormat ff_mpeg2dvd_muxer;

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_mpeg2dvd_muxer_1(void)
{
	return &ff_mpeg2dvd_muxer;
}
