/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/oma.
 *
 * OMA demuxer, muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_oma_demuxer;
extern const struct AVOutputFormat ff_oma_muxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_oma_demuxer_1(void)
{
	return &ff_oma_demuxer;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_oma_muxer_1(void)
{
	return &ff_oma_muxer;
}
