/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/mpeg4.
 *
 * MPEG4 decoder, encoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_mpeg4_decoder;
extern const struct FFCodec ff_mpeg4_encoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_mpeg4_codec_1(void)
{
	return &ff_mpeg4_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_mpeg4_codec_2(void)
{
	return &ff_mpeg4_encoder;
}
