/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/mp2fixed.
 *
 * MP2FIXED encoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_mp2fixed_encoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_mp2fixed_codec_1(void)
{
	return &ff_mp2fixed_encoder;
}
