/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/dfpwm.
 *
 * DFPWM decoder, encoder, demuxer, muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_dfpwm_decoder;
extern const struct AVInputFormat ff_dfpwm_demuxer;
extern const struct FFCodec ff_dfpwm_encoder;
extern const struct AVOutputFormat ff_dfpwm_muxer;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_dfpwm_codec_1(void)
{
	return &ff_dfpwm_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_dfpwm_demuxer_1(void)
{
	return &ff_dfpwm_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_dfpwm_codec_2(void)
{
	return &ff_dfpwm_encoder;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_dfpwm_muxer_1(void)
{
	return &ff_dfpwm_muxer;
}
