/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/xmv-demuxer.
 *
 * XMV demuxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_xmv_demuxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_xmv_demuxer_demuxer_1(void)
{
	return &ff_xmv_demuxer;
}
