/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/wsaud.
 *
 * WSAUD demuxer, muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_wsaud_demuxer;
extern const struct AVOutputFormat ff_wsaud_muxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_wsaud_demuxer_1(void)
{
	return &ff_wsaud_demuxer;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_wsaud_muxer_1(void)
{
	return &ff_wsaud_muxer;
}
