/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/magicyuv.
 *
 * MAGICYUV decoder, encoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_magicyuv_decoder;
extern const struct FFCodec ff_magicyuv_encoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_magicyuv_codec_1(void)
{
	return &ff_magicyuv_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_magicyuv_codec_2(void)
{
	return &ff_magicyuv_encoder;
}
