/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/truemotion2rt.
 *
 * TRUEMOTION2RT decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_truemotion2rt_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_truemotion2rt_codec_1(void)
{
	return &ff_truemotion2rt_decoder;
}
