/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/avui.
 *
 * AVUI decoder, encoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_avui_decoder;
extern const struct FFCodec ff_avui_encoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_avui_codec_1(void)
{
	return &ff_avui_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_avui_codec_2(void)
{
	return &ff_avui_encoder;
}
