/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/truehd.
 *
 * TRUEHD decoder, encoder, demuxer, muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_truehd_decoder;
extern const struct AVInputFormat ff_truehd_demuxer;
extern const struct FFCodec ff_truehd_encoder;
extern const struct AVOutputFormat ff_truehd_muxer;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_truehd_codec_1(void)
{
	return &ff_truehd_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_truehd_demuxer_1(void)
{
	return &ff_truehd_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_truehd_codec_2(void)
{
	return &ff_truehd_encoder;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_truehd_muxer_1(void)
{
	return &ff_truehd_muxer;
}
