/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/rawvideo-muxer.
 *
 * RAWVIDEO muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVOutputFormat ff_rawvideo_muxer;

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_rawvideo_muxer_muxer_1(void)
{
	return &ff_rawvideo_muxer;
}
