/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/dfa-demuxer.
 *
 * DFA demuxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_dfa_demuxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_dfa_demuxer_demuxer_1(void)
{
	return &ff_dfa_demuxer;
}
