/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/wtv-muxer.
 *
 * WTV muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVOutputFormat ff_wtv_muxer;

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_wtv_muxer_muxer_1(void)
{
	return &ff_wtv_muxer;
}
