/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/mpc8-decoder.
 *
 * MPC8 decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_mpc8_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_mpc8_decoder_codec_1(void)
{
	return &ff_mpc8_decoder;
}
