/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/dpcm.
 *
 * DPCM family (7 decoders, 1 encoder).
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_derf_dpcm_decoder;
extern const struct FFCodec ff_gremlin_dpcm_decoder;
extern const struct FFCodec ff_interplay_dpcm_decoder;
extern const struct FFCodec ff_roq_dpcm_decoder;
extern const struct FFCodec ff_roq_dpcm_encoder;
extern const struct FFCodec ff_sdx2_dpcm_decoder;
extern const struct FFCodec ff_sol_dpcm_decoder;
extern const struct FFCodec ff_xan_dpcm_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_dpcm_codec_1(void)
{
	return &ff_derf_dpcm_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_dpcm_codec_2(void)
{
	return &ff_gremlin_dpcm_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_dpcm_codec_3(void)
{
	return &ff_interplay_dpcm_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_dpcm_codec_4(void)
{
	return &ff_roq_dpcm_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_dpcm_codec_5(void)
{
	return &ff_roq_dpcm_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_dpcm_codec_6(void)
{
	return &ff_sdx2_dpcm_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_dpcm_codec_7(void)
{
	return &ff_sol_dpcm_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_dpcm_codec_8(void)
{
	return &ff_xan_dpcm_decoder;
}
