/*
 * Build-time shim for the dpcm extension.
 *
 * `-include`d before any FFmpeg source compiles. We:
 *
 *   1. Pull in upstream's `config.h` + `config_components.h`
 *      so all the HAVE_X / ARCH_X / CONFIG_X defines exist.
 *
 *   2. `#undef` + `#define CONFIG_X 1` for every flag this
 *      extension needs active. C preprocessing rule: last
 *      define wins, so our overrides take effect for all
 *      subsequent source compiles.
 *
 * Without step 2, FFmpeg's per-codec source files DCE their
 * own decode/encode paths because the base build set every
 * `CONFIG_X` to 0.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand.
 */
#ifndef TTN_EXT_DPCM_SHIM_H
#define TTN_EXT_DPCM_SHIM_H

#include "config.h"
#include "config_components.h"

#undef CONFIG_DERF_DPCM_DECODER
#define CONFIG_DERF_DPCM_DECODER 1
#undef CONFIG_GREMLIN_DPCM_DECODER
#define CONFIG_GREMLIN_DPCM_DECODER 1
#undef CONFIG_INTERPLAY_DPCM_DECODER
#define CONFIG_INTERPLAY_DPCM_DECODER 1
#undef CONFIG_ROQ_DPCM_DECODER
#define CONFIG_ROQ_DPCM_DECODER 1
#undef CONFIG_ROQ_DPCM_ENCODER
#define CONFIG_ROQ_DPCM_ENCODER 1
#undef CONFIG_SDX2_DPCM_DECODER
#define CONFIG_SDX2_DPCM_DECODER 1
#undef CONFIG_SOL_DPCM_DECODER
#define CONFIG_SOL_DPCM_DECODER 1
#undef CONFIG_XAN_DPCM_DECODER
#define CONFIG_XAN_DPCM_DECODER 1

#endif
