/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/xsub-decoder.
 *
 * XSUB decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_xsub_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_xsub_decoder_codec_1(void)
{
	return &ff_xsub_decoder;
}
