/*
 * Build-time shim for the ivf extension.
 *
 * `-include`d before any FFmpeg source compiles. We:
 *
 *   1. Pull in upstream's `config.h` + `config_components.h`
 *      so all the HAVE_X / ARCH_X / CONFIG_X defines exist.
 *
 *   2. `#undef` + `#define CONFIG_X 1` for every flag this
 *      extension needs active. C preprocessing rule: last
 *      define wins, so our overrides take effect for all
 *      subsequent source compiles.
 *
 * Without step 2, FFmpeg's per-codec source files DCE their
 * own decode/encode paths because the base build set every
 * `CONFIG_X` to 0.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand.
 */
#ifndef TTN_EXT_IVF_SHIM_H
#define TTN_EXT_IVF_SHIM_H

#include "config.h"
#include "config_components.h"

#undef CONFIG_AV1_METADATA_BSF
#define CONFIG_AV1_METADATA_BSF 1
#undef CONFIG_CBS
#define CONFIG_CBS 1
#undef CONFIG_CBS_AV1
#define CONFIG_CBS_AV1 1
#undef CONFIG_IVF_DEMUXER
#define CONFIG_IVF_DEMUXER 1
#undef CONFIG_IVF_MUXER
#define CONFIG_IVF_MUXER 1
#undef CONFIG_VP9_SUPERFRAME_BSF
#define CONFIG_VP9_SUPERFRAME_BSF 1

#endif
