/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/au.
 *
 * AU demuxer, muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_au_demuxer;
extern const struct AVOutputFormat ff_au_muxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_au_demuxer_1(void)
{
	return &ff_au_demuxer;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_au_muxer_1(void)
{
	return &ff_au_muxer;
}
