/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/v210x.
 *
 * V210X decoder, demuxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_v210x_decoder;
extern const struct AVInputFormat ff_v210x_demuxer;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_v210x_codec_1(void)
{
	return &ff_v210x_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_v210x_demuxer_1(void)
{
	return &ff_v210x_demuxer;
}
