/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/h263.
 *
 * H263 decoder, encoder, demuxer, muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_h263_decoder;
extern const struct AVInputFormat ff_h263_demuxer;
extern const struct FFCodec ff_h263_encoder;
extern const struct AVOutputFormat ff_h263_muxer;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_h263_codec_1(void)
{
	return &ff_h263_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_h263_demuxer_1(void)
{
	return &ff_h263_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_h263_codec_2(void)
{
	return &ff_h263_encoder;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_h263_muxer_1(void)
{
	return &ff_h263_muxer;
}
