/*
 * Build-time shim for the flac-decoder extension.
 *
 * Forces the FFmpeg CONFIG_* flags this extension needs to 1
 * BEFORE the FFmpeg headers pull in config_components.h, so the
 * relevant decode/encode/demux/mux code paths aren't DCE'd by
 * the C preprocessor.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand.
 */
#ifndef TTN_EXT_FLAC_DECODER_SHIM_H
#define TTN_EXT_FLAC_DECODER_SHIM_H

#define CONFIG_FLACDSP 1
#define CONFIG_FLAC_DECODER 1

#endif
