/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/a64.
 *
 * A64 muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVOutputFormat ff_a64_muxer;

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_a64_muxer_1(void)
{
	return &ff_a64_muxer;
}
