/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/adpcm-g726-decoder.
 *
 * ADPCM G726 decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_adpcm_g726_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_g726_decoder_codec_1(void)
{
	return &ff_adpcm_g726_decoder;
}
