/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/targa-y216-decoder.
 *
 * TARGA Y216 decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_targa_y216_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_targa_y216_decoder_codec_1(void)
{
	return &ff_targa_y216_decoder;
}
