/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/ra-288.
 *
 * RA 288 decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_ra_288_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_ra_288_codec_1(void)
{
	return &ff_ra_288_decoder;
}
