/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/apm.
 *
 * APM demuxer, muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_apm_demuxer;
extern const struct AVOutputFormat ff_apm_muxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_apm_demuxer_1(void)
{
	return &ff_apm_demuxer;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_apm_muxer_1(void)
{
	return &ff_apm_muxer;
}
