/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/sol.
 *
 * SOL demuxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_sol_demuxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_sol_demuxer_1(void)
{
	return &ff_sol_demuxer;
}
