/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/nellymoser.
 *
 * NELLYMOSER decoder, encoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_nellymoser_decoder;
extern const struct FFCodec ff_nellymoser_encoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_nellymoser_codec_1(void)
{
	return &ff_nellymoser_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_nellymoser_codec_2(void)
{
	return &ff_nellymoser_encoder;
}
