/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/dca-decoder.
 *
 * DCA decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_dca_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_dca_decoder_codec_1(void)
{
	return &ff_dca_decoder;
}
