/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/dirac.
 *
 * DIRAC decoder, demuxer, muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_dirac_decoder;
extern const struct AVInputFormat ff_dirac_demuxer;
extern const struct AVOutputFormat ff_dirac_muxer;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_dirac_codec_1(void)
{
	return &ff_dirac_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_dirac_demuxer_1(void)
{
	return &ff_dirac_demuxer;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_dirac_muxer_1(void)
{
	return &ff_dirac_muxer;
}
