/**
 * Synthetic fixture builders.
 *
 * Everything here is generated byte-by-byte in code — no commercial
 * game data is used anywhere in this test suite. The helpers
 * deliberately mirror the *storage* layout (tiled blocks) rather than
 * the logical image, so that a test which builds a fixture and then
 * decodes it is actually exercising the tiling and not just agreeing
 * with itself.
 */

import { BTI_HEADER_SIZE } from '../src/index.js';

/** Concatenate byte arrays. */
export function concat(...parts: Uint8Array[]): Uint8Array {
	let total = 0;
	for (const p of parts) total += p.length;
	const out = new Uint8Array(total);
	let o = 0;
	for (const p of parts) {
		out.set(p, o);
		o += p.length;
	}
	return out;
}

/** Big-endian u16 as two bytes. */
export function be16(v: number): Uint8Array {
	return new Uint8Array([(v >> 8) & 0xff, v & 0xff]);
}

/** A block of `count` identical big-endian u16 values. */
export function be16Repeat(v: number, count: number): Uint8Array {
	const out = new Uint8Array(count * 2);
	for (let i = 0; i < count; i++) {
		out[i * 2] = (v >> 8) & 0xff;
		out[i * 2 + 1] = v & 0xff;
	}
	return out;
}

/** Pack an RGB565 value from 8-bit channels (truncating). */
export function rgb565(r: number, g: number, b: number): number {
	return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3);
}

/** RGB5A3 in its opaque 5:5:5 form (top bit set). */
export function rgb555Opaque(r5: number, g5: number, b5: number): number {
	return 0x8000 | (r5 << 10) | (g5 << 5) | b5;
}

/** RGB5A3 in its 3-bit-alpha 4:4:4 form (top bit clear). */
export function rgb4443(a3: number, r4: number, g4: number, b4: number): number {
	return (a3 << 12) | (r4 << 8) | (g4 << 4) | b4;
}

/**
 * Read one RGBA8 texel out of a decoded image.
 * Returns a plain array so `expect(...).toEqual([...])` reads nicely.
 */
export function px(
	pixels: Uint8Array,
	width: number,
	x: number,
	y: number,
): number[] {
	const o = (y * width + x) * 4;
	return [pixels[o], pixels[o + 1], pixels[o + 2], pixels[o + 3]];
}

/**
 * Build one 8-byte CMPR/DXT1 sub-block.
 *
 * `color0`/`color1` are 16-bit RGB565 values written **big-endian**
 * (the GameCube difference from PC DXT1). `rows` is four bytes of
 * 2-bit indices, most-significant bits = left-most texel.
 */
export function dxt1SubBlock(
	color0: number,
	color1: number,
	rows: [number, number, number, number],
): Uint8Array {
	return new Uint8Array([
		(color0 >> 8) & 0xff,
		color0 & 0xff,
		(color1 >> 8) & 0xff,
		color1 & 0xff,
		rows[0],
		rows[1],
		rows[2],
		rows[3],
	]);
}

/** Pack four 2-bit indices into one index byte (left texel first). */
export function idxRow(a: number, b: number, c: number, d: number): number {
	return (a << 6) | (b << 4) | (c << 2) | d;
}

export interface BtiFixtureOptions {
	format: number;
	width: number;
	height: number;
	data: Uint8Array;
	alphaEnabled?: number;
	wrapS?: number;
	wrapT?: number;
	paletteFormat?: number;
	/** Palette entries, already encoded as big-endian 16-bit values. */
	palette?: Uint8Array;
	mipmapCount?: number;
	/** Deliberately override `dataOffset` (for negative tests). */
	dataOffsetOverride?: number;
	/** Extra padding inserted between the header and the palette/data. */
	leadingPadding?: number;
}

/**
 * Build a complete BTI file: 0x20-byte header, then (optional) padding,
 * then the palette, then the image data.
 */
export function makeBti(opts: BtiFixtureOptions): Uint8Array {
	const pad = opts.leadingPadding ?? 0;
	const palette = opts.palette ?? new Uint8Array(0);
	const paletteCount = palette.length / 2;
	const paletteOffset = paletteCount > 0 ? BTI_HEADER_SIZE + pad : 0;
	const dataOffset =
		opts.dataOffsetOverride ?? BTI_HEADER_SIZE + pad + palette.length;

	const header = new Uint8Array(BTI_HEADER_SIZE);
	const view = new DataView(header.buffer);
	header[0x00] = opts.format;
	header[0x01] = opts.alphaEnabled ?? 0;
	view.setUint16(0x02, opts.width, false);
	view.setUint16(0x04, opts.height, false);
	header[0x06] = opts.wrapS ?? 0;
	header[0x07] = opts.wrapT ?? 0;
	header[0x08] = paletteCount > 0 ? 1 : 0;
	header[0x09] = opts.paletteFormat ?? 0;
	view.setUint16(0x0a, paletteCount, false);
	view.setUint32(0x0c, paletteOffset, false);
	view.setUint32(0x10, 0x00000000, false); // borderColor
	header[0x14] = 1; // minFilter
	header[0x15] = 1; // magFilter
	view.setUint16(0x16, 0, false);
	header[0x18] = opts.mipmapCount ?? 1;
	header[0x19] = 0;
	view.setUint16(0x1a, 0, false); // lodBias
	view.setUint32(0x1c, dataOffset, false);

	return concat(header, new Uint8Array(pad), palette, opts.data);
}
