/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/hnm4-video.
 *
 * HNM4 VIDEO decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_hnm4_video_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_hnm4_video_codec_1(void)
{
	return &ff_hnm4_video_decoder;
}
