/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/pcm-s24le-encoder.
 *
 * PCM S24LE encoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_pcm_s24le_encoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_s24le_encoder_codec_1(void)
{
	return &ff_pcm_s24le_encoder;
}
