/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/gsm.
 *
 * GSM decoder, demuxer, muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_gsm_decoder;
extern const struct AVInputFormat ff_gsm_demuxer;
extern const struct AVOutputFormat ff_gsm_muxer;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_gsm_codec_1(void)
{
	return &ff_gsm_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_gsm_demuxer_1(void)
{
	return &ff_gsm_demuxer;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_gsm_muxer_1(void)
{
	return &ff_gsm_muxer;
}
