/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/notchlc.
 *
 * NOTCHLC decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_notchlc_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_notchlc_codec_1(void)
{
	return &ff_notchlc_decoder;
}
