/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/r210.
 *
 * R210 decoder, encoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_r210_decoder;
extern const struct FFCodec ff_r210_encoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_r210_codec_1(void)
{
	return &ff_r210_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_r210_codec_2(void)
{
	return &ff_r210_encoder;
}
