/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/mjpeg-2000-demuxer.
 *
 * MJPEG 2000 demuxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_mjpeg_2000_demuxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_mjpeg_2000_demuxer_demuxer_1(void)
{
	return &ff_mjpeg_2000_demuxer;
}
