/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/webp.
 *
 * WEBP decoder, muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_webp_decoder;
extern const struct AVOutputFormat ff_webp_muxer;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_webp_codec_1(void)
{
	return &ff_webp_decoder;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_webp_muxer_1(void)
{
	return &ff_webp_muxer;
}
