/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/pcm-s16be-planar-decoder.
 *
 * PCM S16BE PLANAR decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_pcm_s16be_planar_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_s16be_planar_decoder_codec_1(void)
{
	return &ff_pcm_s16be_planar_decoder;
}
