/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/indeo5.
 *
 * INDEO5 decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_indeo5_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_indeo5_codec_1(void)
{
	return &ff_indeo5_decoder;
}
