/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/motionpixels.
 *
 * MOTIONPIXELS decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_motionpixels_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_motionpixels_codec_1(void)
{
	return &ff_motionpixels_decoder;
}
