/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/vorbis.
 *
 * VORBIS decoder, encoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_vorbis_decoder;
extern const struct FFCodec ff_vorbis_encoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_vorbis_codec_1(void)
{
	return &ff_vorbis_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_vorbis_codec_2(void)
{
	return &ff_vorbis_encoder;
}
