/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/cavsvideo-demuxer.
 *
 * CAVSVIDEO demuxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_cavsvideo_demuxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_cavsvideo_demuxer_demuxer_1(void)
{
	return &ff_cavsvideo_demuxer;
}
