/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/aac-fixed.
 *
 * AAC FIXED decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_aac_fixed_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_aac_fixed_codec_1(void)
{
	return &ff_aac_fixed_decoder;
}
