/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/asv2.
 *
 * ASV2 decoder, encoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_asv2_decoder;
extern const struct FFCodec ff_asv2_encoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_asv2_codec_1(void)
{
	return &ff_asv2_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_asv2_codec_2(void)
{
	return &ff_asv2_encoder;
}
