/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/wrapped-avframe.
 *
 * WRAPPED AVFRAME decoder, encoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_wrapped_avframe_decoder;
extern const struct FFCodec ff_wrapped_avframe_encoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_wrapped_avframe_codec_1(void)
{
	return &ff_wrapped_avframe_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_wrapped_avframe_codec_2(void)
{
	return &ff_wrapped_avframe_encoder;
}
