/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/opus.
 *
 * OPUS decoder, encoder, muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_opus_decoder;
extern const struct FFCodec ff_opus_encoder;
extern const struct AVOutputFormat ff_opus_muxer;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_opus_codec_1(void)
{
	return &ff_opus_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_opus_codec_2(void)
{
	return &ff_opus_encoder;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_opus_muxer_1(void)
{
	return &ff_opus_muxer;
}
