/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/cavs-decoder.
 *
 * CAVS decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_cavs_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_cavs_decoder_codec_1(void)
{
	return &ff_cavs_decoder;
}
