/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/aac.
 *
 * AAC decoder, encoder, demuxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_aac_decoder;
extern const struct AVInputFormat ff_aac_demuxer;
extern const struct FFCodec ff_aac_encoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_aac_codec_1(void)
{
	return &ff_aac_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_aac_demuxer_1(void)
{
	return &ff_aac_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_aac_codec_2(void)
{
	return &ff_aac_encoder;
}
