/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/qtrle.
 *
 * QTRLE decoder, encoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_qtrle_decoder;
extern const struct FFCodec ff_qtrle_encoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_qtrle_codec_1(void)
{
	return &ff_qtrle_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_qtrle_codec_2(void)
{
	return &ff_qtrle_encoder;
}
