/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/w64.
 *
 * W64 demuxer, muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_w64_demuxer;
extern const struct AVOutputFormat ff_w64_muxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_w64_demuxer_1(void)
{
	return &ff_w64_demuxer;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_w64_muxer_1(void)
{
	return &ff_w64_muxer;
}
