/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/g723-1-muxer.
 *
 * G723 1 muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVOutputFormat ff_g723_1_muxer;

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_g723_1_muxer_muxer_1(void)
{
	return &ff_g723_1_muxer;
}
