/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/flac-demuxer.
 *
 * FLAC (Free Lossless Audio Codec) demuxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_flac_demuxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_flac_demuxer_demuxer_1(void)
{
	return &ff_flac_demuxer;
}
