/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/ac3.
 *
 * AC3 decoder, encoder, demuxer, muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_ac3_decoder;
extern const struct AVInputFormat ff_ac3_demuxer;
extern const struct FFCodec ff_ac3_encoder;
extern const struct AVOutputFormat ff_ac3_muxer;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_ac3_codec_1(void)
{
	return &ff_ac3_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_ac3_demuxer_1(void)
{
	return &ff_ac3_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_ac3_codec_2(void)
{
	return &ff_ac3_encoder;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_ac3_muxer_1(void)
{
	return &ff_ac3_muxer;
}
