/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/h263i.
 *
 * H263I decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_h263i_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_h263i_codec_1(void)
{
	return &ff_h263i_decoder;
}
