/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/rso-muxer.
 *
 * RSO muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVOutputFormat ff_rso_muxer;

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_rso_muxer_muxer_1(void)
{
	return &ff_rso_muxer;
}
