/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/sds.
 *
 * SDS demuxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_sds_demuxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_sds_demuxer_1(void)
{
	return &ff_sds_demuxer;
}
