/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/eac3-encoder.
 *
 * EAC3 encoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_eac3_encoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_eac3_encoder_codec_1(void)
{
	return &ff_eac3_encoder;
}
