/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/subtitle.
 *
 * SUBTITLE family (20 decoders, 10 encoders, 19 demuxers, 9 muxers).
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_aqtitle_demuxer;
extern const struct FFCodec ff_ass_decoder;
extern const struct AVInputFormat ff_ass_demuxer;
extern const struct FFCodec ff_ass_encoder;
extern const struct AVOutputFormat ff_ass_muxer;
extern const struct FFCodec ff_dvbsub_decoder;
extern const struct AVInputFormat ff_dvbsub_demuxer;
extern const struct FFCodec ff_dvbsub_encoder;
extern const struct FFCodec ff_dvdsub_decoder;
extern const struct FFCodec ff_dvdsub_encoder;
extern const struct FFCodec ff_jacosub_decoder;
extern const struct AVInputFormat ff_jacosub_demuxer;
extern const struct AVOutputFormat ff_jacosub_muxer;
extern const struct AVInputFormat ff_lrc_demuxer;
extern const struct AVOutputFormat ff_lrc_muxer;
extern const struct AVInputFormat ff_mcc_demuxer;
extern const struct FFCodec ff_microdvd_decoder;
extern const struct AVInputFormat ff_microdvd_demuxer;
extern const struct AVOutputFormat ff_microdvd_muxer;
extern const struct FFCodec ff_mpl2_decoder;
extern const struct AVInputFormat ff_mpl2_demuxer;
extern const struct FFCodec ff_pgssub_decoder;
extern const struct FFCodec ff_pjs_decoder;
extern const struct AVInputFormat ff_pjs_demuxer;
extern const struct FFCodec ff_realtext_decoder;
extern const struct AVInputFormat ff_realtext_demuxer;
extern const struct FFCodec ff_sami_decoder;
extern const struct AVInputFormat ff_sami_demuxer;
extern const struct AVInputFormat ff_scc_demuxer;
extern const struct AVOutputFormat ff_scc_muxer;
extern const struct FFCodec ff_srt_decoder;
extern const struct AVInputFormat ff_srt_demuxer;
extern const struct FFCodec ff_srt_encoder;
extern const struct AVOutputFormat ff_srt_muxer;
extern const struct FFCodec ff_ssa_decoder;
extern const struct FFCodec ff_ssa_encoder;
extern const struct FFCodec ff_stl_decoder;
extern const struct AVInputFormat ff_stl_demuxer;
extern const struct FFCodec ff_subrip_decoder;
extern const struct FFCodec ff_subrip_encoder;
extern const struct FFCodec ff_subviewer1_decoder;
extern const struct AVInputFormat ff_subviewer1_demuxer;
extern const struct FFCodec ff_subviewer_decoder;
extern const struct AVInputFormat ff_subviewer_demuxer;
extern const struct AVInputFormat ff_sup_demuxer;
extern const struct AVOutputFormat ff_sup_muxer;
extern const struct FFCodec ff_text_decoder;
extern const struct FFCodec ff_text_encoder;
extern const struct FFCodec ff_ttml_encoder;
extern const struct AVOutputFormat ff_ttml_muxer;
extern const struct FFCodec ff_vplayer_decoder;
extern const struct AVInputFormat ff_vplayer_demuxer;
extern const struct FFCodec ff_webvtt_decoder;
extern const struct AVInputFormat ff_webvtt_demuxer;
extern const struct FFCodec ff_webvtt_encoder;
extern const struct AVOutputFormat ff_webvtt_muxer;
extern const struct FFCodec ff_xsub_decoder;
extern const struct FFCodec ff_xsub_encoder;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_subtitle_demuxer_1(void)
{
	return &ff_aqtitle_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_subtitle_codec_1(void)
{
	return &ff_ass_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_subtitle_demuxer_2(void)
{
	return &ff_ass_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_subtitle_codec_2(void)
{
	return &ff_ass_encoder;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_subtitle_muxer_1(void)
{
	return &ff_ass_muxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_subtitle_codec_3(void)
{
	return &ff_dvbsub_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_subtitle_demuxer_3(void)
{
	return &ff_dvbsub_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_subtitle_codec_4(void)
{
	return &ff_dvbsub_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_subtitle_codec_5(void)
{
	return &ff_dvdsub_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_subtitle_codec_6(void)
{
	return &ff_dvdsub_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_subtitle_codec_7(void)
{
	return &ff_jacosub_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_subtitle_demuxer_4(void)
{
	return &ff_jacosub_demuxer;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_subtitle_muxer_2(void)
{
	return &ff_jacosub_muxer;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_subtitle_demuxer_5(void)
{
	return &ff_lrc_demuxer;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_subtitle_muxer_3(void)
{
	return &ff_lrc_muxer;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_subtitle_demuxer_6(void)
{
	return &ff_mcc_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_subtitle_codec_8(void)
{
	return &ff_microdvd_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_subtitle_demuxer_7(void)
{
	return &ff_microdvd_demuxer;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_subtitle_muxer_4(void)
{
	return &ff_microdvd_muxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_subtitle_codec_9(void)
{
	return &ff_mpl2_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_subtitle_demuxer_8(void)
{
	return &ff_mpl2_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_subtitle_codec_10(void)
{
	return &ff_pgssub_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_subtitle_codec_11(void)
{
	return &ff_pjs_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_subtitle_demuxer_9(void)
{
	return &ff_pjs_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_subtitle_codec_12(void)
{
	return &ff_realtext_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_subtitle_demuxer_10(void)
{
	return &ff_realtext_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_subtitle_codec_13(void)
{
	return &ff_sami_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_subtitle_demuxer_11(void)
{
	return &ff_sami_demuxer;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_subtitle_demuxer_12(void)
{
	return &ff_scc_demuxer;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_subtitle_muxer_5(void)
{
	return &ff_scc_muxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_subtitle_codec_14(void)
{
	return &ff_srt_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_subtitle_demuxer_13(void)
{
	return &ff_srt_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_subtitle_codec_15(void)
{
	return &ff_srt_encoder;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_subtitle_muxer_6(void)
{
	return &ff_srt_muxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_subtitle_codec_16(void)
{
	return &ff_ssa_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_subtitle_codec_17(void)
{
	return &ff_ssa_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_subtitle_codec_18(void)
{
	return &ff_stl_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_subtitle_demuxer_14(void)
{
	return &ff_stl_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_subtitle_codec_19(void)
{
	return &ff_subrip_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_subtitle_codec_20(void)
{
	return &ff_subrip_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_subtitle_codec_21(void)
{
	return &ff_subviewer1_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_subtitle_demuxer_15(void)
{
	return &ff_subviewer1_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_subtitle_codec_22(void)
{
	return &ff_subviewer_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_subtitle_demuxer_16(void)
{
	return &ff_subviewer_demuxer;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_subtitle_demuxer_17(void)
{
	return &ff_sup_demuxer;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_subtitle_muxer_7(void)
{
	return &ff_sup_muxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_subtitle_codec_23(void)
{
	return &ff_text_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_subtitle_codec_24(void)
{
	return &ff_text_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_subtitle_codec_25(void)
{
	return &ff_ttml_encoder;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_subtitle_muxer_8(void)
{
	return &ff_ttml_muxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_subtitle_codec_26(void)
{
	return &ff_vplayer_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_subtitle_demuxer_18(void)
{
	return &ff_vplayer_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_subtitle_codec_27(void)
{
	return &ff_webvtt_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_subtitle_demuxer_19(void)
{
	return &ff_webvtt_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_subtitle_codec_28(void)
{
	return &ff_webvtt_encoder;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_subtitle_muxer_9(void)
{
	return &ff_webvtt_muxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_subtitle_codec_29(void)
{
	return &ff_xsub_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_subtitle_codec_30(void)
{
	return &ff_xsub_encoder;
}
