/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/msnwc-tcp-demuxer.
 *
 * MSNWC TCP demuxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_msnwc_tcp_demuxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_msnwc_tcp_demuxer_demuxer_1(void)
{
	return &ff_msnwc_tcp_demuxer;
}
