/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/bmv.
 *
 * BMV demuxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_bmv_demuxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_bmv_demuxer_1(void)
{
	return &ff_bmv_demuxer;
}
