/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/mpeg2video.
 *
 * MPEG2VIDEO decoder, encoder, muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_mpeg2video_decoder;
extern const struct FFCodec ff_mpeg2video_encoder;
extern const struct AVOutputFormat ff_mpeg2video_muxer;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_mpeg2video_codec_1(void)
{
	return &ff_mpeg2video_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_mpeg2video_codec_2(void)
{
	return &ff_mpeg2video_encoder;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_mpeg2video_muxer_1(void)
{
	return &ff_mpeg2video_muxer;
}
