/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/eightsvx-exp.
 *
 * EIGHTSVX EXP decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_eightsvx_exp_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_eightsvx_exp_codec_1(void)
{
	return &ff_eightsvx_exp_decoder;
}
