/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/pcm-f64le-muxer.
 *
 * PCM F64LE muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVOutputFormat ff_pcm_f64le_muxer;

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_pcm_f64le_muxer_muxer_1(void)
{
	return &ff_pcm_f64le_muxer;
}
