/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/eac3.
 *
 * EAC3 decoder, encoder, demuxer, muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_eac3_decoder;
extern const struct AVInputFormat ff_eac3_demuxer;
extern const struct FFCodec ff_eac3_encoder;
extern const struct AVOutputFormat ff_eac3_muxer;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_eac3_codec_1(void)
{
	return &ff_eac3_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_eac3_demuxer_1(void)
{
	return &ff_eac3_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_eac3_codec_2(void)
{
	return &ff_eac3_encoder;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_eac3_muxer_1(void)
{
	return &ff_eac3_muxer;
}
