/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/s302m-decoder.
 *
 * S302M decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_s302m_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_s302m_decoder_codec_1(void)
{
	return &ff_s302m_decoder;
}
