/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/image.
 *
 * IMAGE family (24 decoders, 15 encoders, 1 demuxer).
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_alias_pix_decoder;
extern const struct FFCodec ff_alias_pix_encoder;
extern const struct FFCodec ff_bitpacked_decoder;
extern const struct AVInputFormat ff_bitpacked_demuxer;
extern const struct FFCodec ff_bitpacked_encoder;
extern const struct FFCodec ff_brender_pix_decoder;
extern const struct FFCodec ff_cri_decoder;
extern const struct FFCodec ff_dpx_decoder;
extern const struct FFCodec ff_dpx_encoder;
extern const struct FFCodec ff_gem_decoder;
extern const struct FFCodec ff_pam_decoder;
extern const struct FFCodec ff_pam_encoder;
extern const struct FFCodec ff_pbm_decoder;
extern const struct FFCodec ff_pbm_encoder;
extern const struct FFCodec ff_pcx_decoder;
extern const struct FFCodec ff_pcx_encoder;
extern const struct FFCodec ff_pfm_decoder;
extern const struct FFCodec ff_pfm_encoder;
extern const struct FFCodec ff_pgm_decoder;
extern const struct FFCodec ff_pgm_encoder;
extern const struct FFCodec ff_pgmyuv_decoder;
extern const struct FFCodec ff_pgmyuv_encoder;
extern const struct FFCodec ff_pgx_decoder;
extern const struct FFCodec ff_photocd_decoder;
extern const struct FFCodec ff_pictor_decoder;
extern const struct FFCodec ff_ppm_decoder;
extern const struct FFCodec ff_ppm_encoder;
extern const struct FFCodec ff_psd_decoder;
extern const struct FFCodec ff_qdraw_decoder;
extern const struct FFCodec ff_sgi_decoder;
extern const struct FFCodec ff_sgi_encoder;
extern const struct FFCodec ff_sunrast_decoder;
extern const struct FFCodec ff_sunrast_encoder;
extern const struct FFCodec ff_vbn_decoder;
extern const struct FFCodec ff_vbn_encoder;
extern const struct FFCodec ff_xbm_decoder;
extern const struct FFCodec ff_xbm_encoder;
extern const struct FFCodec ff_xpm_decoder;
extern const struct FFCodec ff_xwd_decoder;
extern const struct FFCodec ff_xwd_encoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_image_codec_1(void)
{
	return &ff_alias_pix_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_image_codec_2(void)
{
	return &ff_alias_pix_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_image_codec_3(void)
{
	return &ff_bitpacked_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_image_demuxer_1(void)
{
	return &ff_bitpacked_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_image_codec_4(void)
{
	return &ff_bitpacked_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_image_codec_5(void)
{
	return &ff_brender_pix_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_image_codec_6(void)
{
	return &ff_cri_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_image_codec_7(void)
{
	return &ff_dpx_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_image_codec_8(void)
{
	return &ff_dpx_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_image_codec_9(void)
{
	return &ff_gem_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_image_codec_10(void)
{
	return &ff_pam_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_image_codec_11(void)
{
	return &ff_pam_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_image_codec_12(void)
{
	return &ff_pbm_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_image_codec_13(void)
{
	return &ff_pbm_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_image_codec_14(void)
{
	return &ff_pcx_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_image_codec_15(void)
{
	return &ff_pcx_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_image_codec_16(void)
{
	return &ff_pfm_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_image_codec_17(void)
{
	return &ff_pfm_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_image_codec_18(void)
{
	return &ff_pgm_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_image_codec_19(void)
{
	return &ff_pgm_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_image_codec_20(void)
{
	return &ff_pgmyuv_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_image_codec_21(void)
{
	return &ff_pgmyuv_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_image_codec_22(void)
{
	return &ff_pgx_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_image_codec_23(void)
{
	return &ff_photocd_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_image_codec_24(void)
{
	return &ff_pictor_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_image_codec_25(void)
{
	return &ff_ppm_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_image_codec_26(void)
{
	return &ff_ppm_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_image_codec_27(void)
{
	return &ff_psd_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_image_codec_28(void)
{
	return &ff_qdraw_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_image_codec_29(void)
{
	return &ff_sgi_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_image_codec_30(void)
{
	return &ff_sgi_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_image_codec_31(void)
{
	return &ff_sunrast_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_image_codec_32(void)
{
	return &ff_sunrast_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_image_codec_33(void)
{
	return &ff_vbn_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_image_codec_34(void)
{
	return &ff_vbn_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_image_codec_35(void)
{
	return &ff_xbm_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_image_codec_36(void)
{
	return &ff_xbm_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_image_codec_37(void)
{
	return &ff_xpm_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_image_codec_38(void)
{
	return &ff_xwd_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_image_codec_39(void)
{
	return &ff_xwd_encoder;
}
