/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/roq.
 *
 * ROQ decoder, encoder, demuxer, muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_roq_decoder;
extern const struct AVInputFormat ff_roq_demuxer;
extern const struct FFCodec ff_roq_encoder;
extern const struct AVOutputFormat ff_roq_muxer;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_roq_codec_1(void)
{
	return &ff_roq_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_roq_demuxer_1(void)
{
	return &ff_roq_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_roq_codec_2(void)
{
	return &ff_roq_encoder;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_roq_muxer_1(void)
{
	return &ff_roq_muxer;
}
