/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/pcm-u32le-decoder.
 *
 * PCM U32LE decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_pcm_u32le_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_u32le_decoder_codec_1(void)
{
	return &ff_pcm_u32le_decoder;
}
