/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/ljpeg-encoder.
 *
 * LJPEG encoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_ljpeg_encoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_ljpeg_encoder_codec_1(void)
{
	return &ff_ljpeg_encoder;
}
