/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/avs2.
 *
 * AVS2 demuxer, muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_avs2_demuxer;
extern const struct AVOutputFormat ff_avs2_muxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_avs2_demuxer_1(void)
{
	return &ff_avs2_demuxer;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_avs2_muxer_1(void)
{
	return &ff_avs2_muxer;
}
