/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/vp6.
 *
 * VP6 decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_vp6_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_vp6_codec_1(void)
{
	return &ff_vp6_decoder;
}
