/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/adpcm-adx-encoder.
 *
 * ADPCM ADX encoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_adpcm_adx_encoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_adx_encoder_codec_1(void)
{
	return &ff_adpcm_adx_encoder;
}
