/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/wmav2-encoder.
 *
 * WMAV2 encoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_wmav2_encoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_wmav2_encoder_codec_1(void)
{
	return &ff_wmav2_encoder;
}
