/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/sunrast-decoder.
 *
 * SUNRAST decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_sunrast_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_sunrast_decoder_codec_1(void)
{
	return &ff_sunrast_decoder;
}
