/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/svq3.
 *
 * SVQ3 decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_svq3_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_svq3_codec_1(void)
{
	return &ff_svq3_decoder;
}
