/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/mp2.
 *
 * MP2 decoder, encoder, muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_mp2_decoder;
extern const struct FFCodec ff_mp2_encoder;
extern const struct AVOutputFormat ff_mp2_muxer;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_mp2_codec_1(void)
{
	return &ff_mp2_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_mp2_codec_2(void)
{
	return &ff_mp2_encoder;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_mp2_muxer_1(void)
{
	return &ff_mp2_muxer;
}
