/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/bit-muxer.
 *
 * BIT muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVOutputFormat ff_bit_muxer;

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_bit_muxer_muxer_1(void)
{
	return &ff_bit_muxer;
}
