/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/adx.
 *
 * ADX demuxer, muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_adx_demuxer;
extern const struct AVOutputFormat ff_adx_muxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_adx_demuxer_1(void)
{
	return &ff_adx_demuxer;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_adx_muxer_1(void)
{
	return &ff_adx_muxer;
}
