/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/hevc.
 *
 * HEVC decoder, demuxer, muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_hevc_decoder;
extern const struct AVInputFormat ff_hevc_demuxer;
extern const struct AVOutputFormat ff_hevc_muxer;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_hevc_codec_1(void)
{
	return &ff_hevc_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_hevc_demuxer_1(void)
{
	return &ff_hevc_demuxer;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_hevc_muxer_1(void)
{
	return &ff_hevc_muxer;
}
