/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/av1.
 *
 * AV1 decoder, demuxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_av1_decoder;
extern const struct AVInputFormat ff_av1_demuxer;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_av1_codec_1(void)
{
	return &ff_av1_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_av1_demuxer_1(void)
{
	return &ff_av1_demuxer;
}
