/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/subviewer1-demuxer.
 *
 * SUBVIEWER1 demuxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_subviewer1_demuxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_subviewer1_demuxer_demuxer_1(void)
{
	return &ff_subviewer1_demuxer;
}
