/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/h261-decoder.
 *
 * H261 decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_h261_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_h261_decoder_codec_1(void)
{
	return &ff_h261_decoder;
}
