/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/rm.
 *
 * RM demuxer, muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_rm_demuxer;
extern const struct AVOutputFormat ff_rm_muxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_rm_demuxer_1(void)
{
	return &ff_rm_demuxer;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_rm_muxer_1(void)
{
	return &ff_rm_muxer;
}
