/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/interplay-acm-decoder.
 *
 * INTERPLAY ACM decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_interplay_acm_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_interplay_acm_decoder_codec_1(void)
{
	return &ff_interplay_acm_decoder;
}
