/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/v410-decoder.
 *
 * V410 decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_v410_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_v410_decoder_codec_1(void)
{
	return &ff_v410_decoder;
}
