/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/vp8-decoder.
 *
 * VP8 decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_vp8_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_vp8_decoder_codec_1(void)
{
	return &ff_vp8_decoder;
}
