/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/data.
 *
 * DATA demuxer, muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_data_demuxer;
extern const struct AVOutputFormat ff_data_muxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_data_demuxer_1(void)
{
	return &ff_data_demuxer;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_data_muxer_1(void)
{
	return &ff_data_muxer;
}
