/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/v410.
 *
 * V410 decoder, encoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_v410_decoder;
extern const struct FFCodec ff_v410_encoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_v410_codec_1(void)
{
	return &ff_v410_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_v410_codec_2(void)
{
	return &ff_v410_encoder;
}
