/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/adpcm-zork-decoder.
 *
 * ADPCM ZORK decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_adpcm_zork_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_adpcm_zork_decoder_codec_1(void)
{
	return &ff_adpcm_zork_decoder;
}
