/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/hca.
 *
 * HCA decoder, demuxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_hca_decoder;
extern const struct AVInputFormat ff_hca_demuxer;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_hca_codec_1(void)
{
	return &ff_hca_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_hca_demuxer_1(void)
{
	return &ff_hca_demuxer;
}
