/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/mpeg1video-muxer.
 *
 * MPEG1VIDEO muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVOutputFormat ff_mpeg1video_muxer;

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_mpeg1video_muxer_muxer_1(void)
{
	return &ff_mpeg1video_muxer;
}
