/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/bmv-audio-decoder.
 *
 * BMV AUDIO decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_bmv_audio_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_bmv_audio_decoder_codec_1(void)
{
	return &ff_bmv_audio_decoder;
}
