/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/zero12v.
 *
 * ZERO12V decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_zero12v_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_zero12v_codec_1(void)
{
	return &ff_zero12v_decoder;
}
