/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/mace6.
 *
 * MACE6 decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_mace6_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_mace6_codec_1(void)
{
	return &ff_mace6_decoder;
}
