/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/mlp-muxer.
 *
 * MLP muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVOutputFormat ff_mlp_muxer;

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_mlp_muxer_muxer_1(void)
{
	return &ff_mlp_muxer;
}
