/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/alias-pix-decoder.
 *
 * ALIAS PIX decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_alias_pix_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_alias_pix_decoder_codec_1(void)
{
	return &ff_alias_pix_decoder;
}
