/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/hcom.
 *
 * HCOM decoder, demuxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_hcom_decoder;
extern const struct AVInputFormat ff_hcom_demuxer;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_hcom_codec_1(void)
{
	return &ff_hcom_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_hcom_demuxer_1(void)
{
	return &ff_hcom_demuxer;
}
