/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/ivr-demuxer.
 *
 * IVR demuxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_ivr_demuxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_ivr_demuxer_demuxer_1(void)
{
	return &ff_ivr_demuxer;
}
