/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/ac3-fixed.
 *
 * AC3 FIXED decoder, encoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_ac3_fixed_decoder;
extern const struct FFCodec ff_ac3_fixed_encoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_ac3_fixed_codec_1(void)
{
	return &ff_ac3_fixed_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_ac3_fixed_codec_2(void)
{
	return &ff_ac3_fixed_encoder;
}
