/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/dss-sp.
 *
 * DSS SP decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_dss_sp_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_dss_sp_codec_1(void)
{
	return &ff_dss_sp_decoder;
}
