/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/mov.
 *
 * MOV demuxer, muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_mov_demuxer;
extern const struct AVOutputFormat ff_mov_muxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_mov_demuxer_1(void)
{
	return &ff_mov_demuxer;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_mov_muxer_1(void)
{
	return &ff_mov_muxer;
}
