/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/h261.
 *
 * H261 decoder, encoder, demuxer, muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_h261_decoder;
extern const struct AVInputFormat ff_h261_demuxer;
extern const struct FFCodec ff_h261_encoder;
extern const struct AVOutputFormat ff_h261_muxer;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_h261_codec_1(void)
{
	return &ff_h261_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_h261_demuxer_1(void)
{
	return &ff_h261_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_h261_codec_2(void)
{
	return &ff_h261_encoder;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_h261_muxer_1(void)
{
	return &ff_h261_muxer;
}
