/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/argo-brp-demuxer.
 *
 * ARGO BRP demuxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_argo_brp_demuxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_argo_brp_demuxer_demuxer_1(void)
{
	return &ff_argo_brp_demuxer;
}
