/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/yuv4.
 *
 * YUV4 decoder, encoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_yuv4_decoder;
extern const struct FFCodec ff_yuv4_encoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_yuv4_codec_1(void)
{
	return &ff_yuv4_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_yuv4_codec_2(void)
{
	return &ff_yuv4_encoder;
}
