/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/mp3on4.
 *
 * MP3ON4 decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_mp3on4_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_mp3on4_codec_1(void)
{
	return &ff_mp3on4_decoder;
}
