/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/wavpack-encoder.
 *
 * WAVPACK encoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_wavpack_encoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_wavpack_encoder_codec_1(void)
{
	return &ff_wavpack_encoder;
}
