/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/smc.
 *
 * SMC decoder, encoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_smc_decoder;
extern const struct FFCodec ff_smc_encoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_smc_codec_1(void)
{
	return &ff_smc_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_smc_codec_2(void)
{
	return &ff_smc_encoder;
}
