/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/cinepak-encoder.
 *
 * CINEPAK encoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_cinepak_encoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_cinepak_encoder_codec_1(void)
{
	return &ff_cinepak_encoder;
}
