/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/vc1t-muxer.
 *
 * VC1T muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVOutputFormat ff_vc1t_muxer;

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_vc1t_muxer_muxer_1(void)
{
	return &ff_vc1t_muxer;
}
