/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/smjpeg-muxer.
 *
 * SMJPEG muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVOutputFormat ff_smjpeg_muxer;

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_smjpeg_muxer_muxer_1(void)
{
	return &ff_smjpeg_muxer;
}
