/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/msa1.
 *
 * MSA1 decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_msa1_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_msa1_codec_1(void)
{
	return &ff_msa1_decoder;
}
