/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/rawvideo.
 *
 * RAWVIDEO decoder, encoder, demuxer, muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_rawvideo_decoder;
extern const struct AVInputFormat ff_rawvideo_demuxer;
extern const struct FFCodec ff_rawvideo_encoder;
extern const struct AVOutputFormat ff_rawvideo_muxer;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_rawvideo_codec_1(void)
{
	return &ff_rawvideo_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_rawvideo_demuxer_1(void)
{
	return &ff_rawvideo_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_rawvideo_codec_2(void)
{
	return &ff_rawvideo_encoder;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_rawvideo_muxer_1(void)
{
	return &ff_rawvideo_muxer;
}
