/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/image2-muxer.
 *
 * IMAGE2 muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVOutputFormat ff_image2_muxer;

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_image2_muxer_muxer_1(void)
{
	return &ff_image2_muxer;
}
