/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/on2avc.
 *
 * ON2AVC decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_on2avc_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_on2avc_codec_1(void)
{
	return &ff_on2avc_decoder;
}
