/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/caf-demuxer.
 *
 * CAF demuxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_caf_demuxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_caf_demuxer_demuxer_1(void)
{
	return &ff_caf_demuxer;
}
