/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/kgv1.
 *
 * KGV1 decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_kgv1_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_kgv1_codec_1(void)
{
	return &ff_kgv1_decoder;
}
