/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/image-exr-pipe-demuxer.
 *
 * IMAGE EXR PIPE demuxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_image_exr_pipe_demuxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_image_exr_pipe_demuxer_demuxer_1(void)
{
	return &ff_image_exr_pipe_demuxer;
}
