/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/m4v.
 *
 * M4V demuxer, muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_m4v_demuxer;
extern const struct AVOutputFormat ff_m4v_muxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_m4v_demuxer_1(void)
{
	return &ff_m4v_demuxer;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_m4v_muxer_1(void)
{
	return &ff_m4v_muxer;
}
