/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/snow.
 *
 * SNOW decoder, encoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_snow_decoder;
extern const struct FFCodec ff_snow_encoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_snow_codec_1(void)
{
	return &ff_snow_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_snow_codec_2(void)
{
	return &ff_snow_encoder;
}
