/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/g723-1-demuxer.
 *
 * G723 1 demuxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_g723_1_demuxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_g723_1_demuxer_demuxer_1(void)
{
	return &ff_g723_1_demuxer;
}
