/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/dhav-demuxer.
 *
 * DHAV demuxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_dhav_demuxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_dhav_demuxer_demuxer_1(void)
{
	return &ff_dhav_demuxer;
}
