/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/pcm.
 *
 * PCM family (35 decoders, 31 encoders, 21 demuxers, 21 muxers).
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_pcm_alaw_decoder;
extern const struct AVInputFormat ff_pcm_alaw_demuxer;
extern const struct FFCodec ff_pcm_alaw_encoder;
extern const struct AVOutputFormat ff_pcm_alaw_muxer;
extern const struct FFCodec ff_pcm_bluray_decoder;
extern const struct FFCodec ff_pcm_bluray_encoder;
extern const struct FFCodec ff_pcm_dvd_decoder;
extern const struct FFCodec ff_pcm_dvd_encoder;
extern const struct FFCodec ff_pcm_f16le_decoder;
extern const struct FFCodec ff_pcm_f24le_decoder;
extern const struct FFCodec ff_pcm_f32be_decoder;
extern const struct AVInputFormat ff_pcm_f32be_demuxer;
extern const struct FFCodec ff_pcm_f32be_encoder;
extern const struct AVOutputFormat ff_pcm_f32be_muxer;
extern const struct FFCodec ff_pcm_f32le_decoder;
extern const struct AVInputFormat ff_pcm_f32le_demuxer;
extern const struct FFCodec ff_pcm_f32le_encoder;
extern const struct AVOutputFormat ff_pcm_f32le_muxer;
extern const struct FFCodec ff_pcm_f64be_decoder;
extern const struct AVInputFormat ff_pcm_f64be_demuxer;
extern const struct FFCodec ff_pcm_f64be_encoder;
extern const struct AVOutputFormat ff_pcm_f64be_muxer;
extern const struct FFCodec ff_pcm_f64le_decoder;
extern const struct AVInputFormat ff_pcm_f64le_demuxer;
extern const struct FFCodec ff_pcm_f64le_encoder;
extern const struct AVOutputFormat ff_pcm_f64le_muxer;
extern const struct FFCodec ff_pcm_lxf_decoder;
extern const struct FFCodec ff_pcm_mulaw_decoder;
extern const struct AVInputFormat ff_pcm_mulaw_demuxer;
extern const struct FFCodec ff_pcm_mulaw_encoder;
extern const struct AVOutputFormat ff_pcm_mulaw_muxer;
extern const struct FFCodec ff_pcm_s16be_decoder;
extern const struct AVInputFormat ff_pcm_s16be_demuxer;
extern const struct FFCodec ff_pcm_s16be_encoder;
extern const struct AVOutputFormat ff_pcm_s16be_muxer;
extern const struct FFCodec ff_pcm_s16be_planar_decoder;
extern const struct FFCodec ff_pcm_s16be_planar_encoder;
extern const struct FFCodec ff_pcm_s16le_decoder;
extern const struct AVInputFormat ff_pcm_s16le_demuxer;
extern const struct FFCodec ff_pcm_s16le_encoder;
extern const struct AVOutputFormat ff_pcm_s16le_muxer;
extern const struct FFCodec ff_pcm_s16le_planar_decoder;
extern const struct FFCodec ff_pcm_s16le_planar_encoder;
extern const struct FFCodec ff_pcm_s24be_decoder;
extern const struct AVInputFormat ff_pcm_s24be_demuxer;
extern const struct FFCodec ff_pcm_s24be_encoder;
extern const struct AVOutputFormat ff_pcm_s24be_muxer;
extern const struct FFCodec ff_pcm_s24daud_decoder;
extern const struct FFCodec ff_pcm_s24daud_encoder;
extern const struct FFCodec ff_pcm_s24le_decoder;
extern const struct AVInputFormat ff_pcm_s24le_demuxer;
extern const struct FFCodec ff_pcm_s24le_encoder;
extern const struct AVOutputFormat ff_pcm_s24le_muxer;
extern const struct FFCodec ff_pcm_s24le_planar_decoder;
extern const struct FFCodec ff_pcm_s24le_planar_encoder;
extern const struct FFCodec ff_pcm_s32be_decoder;
extern const struct AVInputFormat ff_pcm_s32be_demuxer;
extern const struct FFCodec ff_pcm_s32be_encoder;
extern const struct AVOutputFormat ff_pcm_s32be_muxer;
extern const struct FFCodec ff_pcm_s32le_decoder;
extern const struct AVInputFormat ff_pcm_s32le_demuxer;
extern const struct FFCodec ff_pcm_s32le_encoder;
extern const struct AVOutputFormat ff_pcm_s32le_muxer;
extern const struct FFCodec ff_pcm_s32le_planar_decoder;
extern const struct FFCodec ff_pcm_s32le_planar_encoder;
extern const struct FFCodec ff_pcm_s64be_decoder;
extern const struct FFCodec ff_pcm_s64be_encoder;
extern const struct FFCodec ff_pcm_s64le_decoder;
extern const struct FFCodec ff_pcm_s64le_encoder;
extern const struct FFCodec ff_pcm_s8_decoder;
extern const struct AVInputFormat ff_pcm_s8_demuxer;
extern const struct FFCodec ff_pcm_s8_encoder;
extern const struct AVOutputFormat ff_pcm_s8_muxer;
extern const struct FFCodec ff_pcm_s8_planar_decoder;
extern const struct FFCodec ff_pcm_s8_planar_encoder;
extern const struct FFCodec ff_pcm_sga_decoder;
extern const struct FFCodec ff_pcm_u16be_decoder;
extern const struct AVInputFormat ff_pcm_u16be_demuxer;
extern const struct FFCodec ff_pcm_u16be_encoder;
extern const struct AVOutputFormat ff_pcm_u16be_muxer;
extern const struct FFCodec ff_pcm_u16le_decoder;
extern const struct AVInputFormat ff_pcm_u16le_demuxer;
extern const struct FFCodec ff_pcm_u16le_encoder;
extern const struct AVOutputFormat ff_pcm_u16le_muxer;
extern const struct FFCodec ff_pcm_u24be_decoder;
extern const struct AVInputFormat ff_pcm_u24be_demuxer;
extern const struct FFCodec ff_pcm_u24be_encoder;
extern const struct AVOutputFormat ff_pcm_u24be_muxer;
extern const struct FFCodec ff_pcm_u24le_decoder;
extern const struct AVInputFormat ff_pcm_u24le_demuxer;
extern const struct FFCodec ff_pcm_u24le_encoder;
extern const struct AVOutputFormat ff_pcm_u24le_muxer;
extern const struct FFCodec ff_pcm_u32be_decoder;
extern const struct AVInputFormat ff_pcm_u32be_demuxer;
extern const struct FFCodec ff_pcm_u32be_encoder;
extern const struct AVOutputFormat ff_pcm_u32be_muxer;
extern const struct FFCodec ff_pcm_u32le_decoder;
extern const struct AVInputFormat ff_pcm_u32le_demuxer;
extern const struct FFCodec ff_pcm_u32le_encoder;
extern const struct AVOutputFormat ff_pcm_u32le_muxer;
extern const struct FFCodec ff_pcm_u8_decoder;
extern const struct AVInputFormat ff_pcm_u8_demuxer;
extern const struct FFCodec ff_pcm_u8_encoder;
extern const struct AVOutputFormat ff_pcm_u8_muxer;
extern const struct FFCodec ff_pcm_vidc_decoder;
extern const struct AVInputFormat ff_pcm_vidc_demuxer;
extern const struct FFCodec ff_pcm_vidc_encoder;
extern const struct AVOutputFormat ff_pcm_vidc_muxer;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_1(void)
{
	return &ff_pcm_alaw_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_pcm_demuxer_1(void)
{
	return &ff_pcm_alaw_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_2(void)
{
	return &ff_pcm_alaw_encoder;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_pcm_muxer_1(void)
{
	return &ff_pcm_alaw_muxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_3(void)
{
	return &ff_pcm_bluray_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_4(void)
{
	return &ff_pcm_bluray_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_5(void)
{
	return &ff_pcm_dvd_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_6(void)
{
	return &ff_pcm_dvd_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_7(void)
{
	return &ff_pcm_f16le_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_8(void)
{
	return &ff_pcm_f24le_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_9(void)
{
	return &ff_pcm_f32be_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_pcm_demuxer_2(void)
{
	return &ff_pcm_f32be_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_10(void)
{
	return &ff_pcm_f32be_encoder;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_pcm_muxer_2(void)
{
	return &ff_pcm_f32be_muxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_11(void)
{
	return &ff_pcm_f32le_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_pcm_demuxer_3(void)
{
	return &ff_pcm_f32le_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_12(void)
{
	return &ff_pcm_f32le_encoder;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_pcm_muxer_3(void)
{
	return &ff_pcm_f32le_muxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_13(void)
{
	return &ff_pcm_f64be_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_pcm_demuxer_4(void)
{
	return &ff_pcm_f64be_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_14(void)
{
	return &ff_pcm_f64be_encoder;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_pcm_muxer_4(void)
{
	return &ff_pcm_f64be_muxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_15(void)
{
	return &ff_pcm_f64le_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_pcm_demuxer_5(void)
{
	return &ff_pcm_f64le_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_16(void)
{
	return &ff_pcm_f64le_encoder;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_pcm_muxer_5(void)
{
	return &ff_pcm_f64le_muxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_17(void)
{
	return &ff_pcm_lxf_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_18(void)
{
	return &ff_pcm_mulaw_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_pcm_demuxer_6(void)
{
	return &ff_pcm_mulaw_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_19(void)
{
	return &ff_pcm_mulaw_encoder;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_pcm_muxer_6(void)
{
	return &ff_pcm_mulaw_muxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_20(void)
{
	return &ff_pcm_s16be_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_pcm_demuxer_7(void)
{
	return &ff_pcm_s16be_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_21(void)
{
	return &ff_pcm_s16be_encoder;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_pcm_muxer_7(void)
{
	return &ff_pcm_s16be_muxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_22(void)
{
	return &ff_pcm_s16be_planar_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_23(void)
{
	return &ff_pcm_s16be_planar_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_24(void)
{
	return &ff_pcm_s16le_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_pcm_demuxer_8(void)
{
	return &ff_pcm_s16le_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_25(void)
{
	return &ff_pcm_s16le_encoder;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_pcm_muxer_8(void)
{
	return &ff_pcm_s16le_muxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_26(void)
{
	return &ff_pcm_s16le_planar_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_27(void)
{
	return &ff_pcm_s16le_planar_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_28(void)
{
	return &ff_pcm_s24be_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_pcm_demuxer_9(void)
{
	return &ff_pcm_s24be_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_29(void)
{
	return &ff_pcm_s24be_encoder;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_pcm_muxer_9(void)
{
	return &ff_pcm_s24be_muxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_30(void)
{
	return &ff_pcm_s24daud_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_31(void)
{
	return &ff_pcm_s24daud_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_32(void)
{
	return &ff_pcm_s24le_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_pcm_demuxer_10(void)
{
	return &ff_pcm_s24le_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_33(void)
{
	return &ff_pcm_s24le_encoder;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_pcm_muxer_10(void)
{
	return &ff_pcm_s24le_muxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_34(void)
{
	return &ff_pcm_s24le_planar_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_35(void)
{
	return &ff_pcm_s24le_planar_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_36(void)
{
	return &ff_pcm_s32be_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_pcm_demuxer_11(void)
{
	return &ff_pcm_s32be_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_37(void)
{
	return &ff_pcm_s32be_encoder;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_pcm_muxer_11(void)
{
	return &ff_pcm_s32be_muxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_38(void)
{
	return &ff_pcm_s32le_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_pcm_demuxer_12(void)
{
	return &ff_pcm_s32le_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_39(void)
{
	return &ff_pcm_s32le_encoder;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_pcm_muxer_12(void)
{
	return &ff_pcm_s32le_muxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_40(void)
{
	return &ff_pcm_s32le_planar_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_41(void)
{
	return &ff_pcm_s32le_planar_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_42(void)
{
	return &ff_pcm_s64be_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_43(void)
{
	return &ff_pcm_s64be_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_44(void)
{
	return &ff_pcm_s64le_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_45(void)
{
	return &ff_pcm_s64le_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_46(void)
{
	return &ff_pcm_s8_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_pcm_demuxer_13(void)
{
	return &ff_pcm_s8_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_47(void)
{
	return &ff_pcm_s8_encoder;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_pcm_muxer_13(void)
{
	return &ff_pcm_s8_muxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_48(void)
{
	return &ff_pcm_s8_planar_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_49(void)
{
	return &ff_pcm_s8_planar_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_50(void)
{
	return &ff_pcm_sga_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_51(void)
{
	return &ff_pcm_u16be_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_pcm_demuxer_14(void)
{
	return &ff_pcm_u16be_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_52(void)
{
	return &ff_pcm_u16be_encoder;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_pcm_muxer_14(void)
{
	return &ff_pcm_u16be_muxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_53(void)
{
	return &ff_pcm_u16le_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_pcm_demuxer_15(void)
{
	return &ff_pcm_u16le_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_54(void)
{
	return &ff_pcm_u16le_encoder;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_pcm_muxer_15(void)
{
	return &ff_pcm_u16le_muxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_55(void)
{
	return &ff_pcm_u24be_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_pcm_demuxer_16(void)
{
	return &ff_pcm_u24be_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_56(void)
{
	return &ff_pcm_u24be_encoder;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_pcm_muxer_16(void)
{
	return &ff_pcm_u24be_muxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_57(void)
{
	return &ff_pcm_u24le_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_pcm_demuxer_17(void)
{
	return &ff_pcm_u24le_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_58(void)
{
	return &ff_pcm_u24le_encoder;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_pcm_muxer_17(void)
{
	return &ff_pcm_u24le_muxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_59(void)
{
	return &ff_pcm_u32be_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_pcm_demuxer_18(void)
{
	return &ff_pcm_u32be_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_60(void)
{
	return &ff_pcm_u32be_encoder;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_pcm_muxer_18(void)
{
	return &ff_pcm_u32be_muxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_61(void)
{
	return &ff_pcm_u32le_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_pcm_demuxer_19(void)
{
	return &ff_pcm_u32le_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_62(void)
{
	return &ff_pcm_u32le_encoder;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_pcm_muxer_19(void)
{
	return &ff_pcm_u32le_muxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_63(void)
{
	return &ff_pcm_u8_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_pcm_demuxer_20(void)
{
	return &ff_pcm_u8_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_64(void)
{
	return &ff_pcm_u8_encoder;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_pcm_muxer_20(void)
{
	return &ff_pcm_u8_muxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_65(void)
{
	return &ff_pcm_vidc_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_pcm_demuxer_21(void)
{
	return &ff_pcm_vidc_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_codec_66(void)
{
	return &ff_pcm_vidc_encoder;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_pcm_muxer_21(void)
{
	return &ff_pcm_vidc_muxer;
}
