/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/aptx-hd-demuxer.
 *
 * APTX HD demuxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_aptx_hd_demuxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_aptx_hd_demuxer_demuxer_1(void)
{
	return &ff_aptx_hd_demuxer;
}
