/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/escape124.
 *
 * ESCAPE124 decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_escape124_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_escape124_codec_1(void)
{
	return &ff_escape124_decoder;
}
