/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/dca-encoder.
 *
 * DCA encoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_dca_encoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_dca_encoder_codec_1(void)
{
	return &ff_dca_encoder;
}
