/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/framehash.
 *
 * FRAMEHASH muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVOutputFormat ff_framehash_muxer;

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_framehash_muxer_1(void)
{
	return &ff_framehash_muxer;
}
