/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/gif-encoder.
 *
 * GIF encoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_gif_encoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_gif_encoder_codec_1(void)
{
	return &ff_gif_encoder;
}
