/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/rl2.
 *
 * RL2 decoder, demuxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_rl2_decoder;
extern const struct AVInputFormat ff_rl2_demuxer;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_rl2_codec_1(void)
{
	return &ff_rl2_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_rl2_demuxer_1(void)
{
	return &ff_rl2_demuxer;
}
