/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/gsm-ms.
 *
 * GSM MS decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_gsm_ms_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_gsm_ms_codec_1(void)
{
	return &ff_gsm_ms_decoder;
}
