/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/xan-wc4.
 *
 * XAN WC4 decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_xan_wc4_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_xan_wc4_codec_1(void)
{
	return &ff_xan_wc4_decoder;
}
