/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/dsd-msbf-planar-decoder.
 *
 * DSD MSBF PLANAR decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_dsd_msbf_planar_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_dsd_msbf_planar_decoder_codec_1(void)
{
	return &ff_dsd_msbf_planar_decoder;
}
