/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/h264-muxer.
 *
 * H264 muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVOutputFormat ff_h264_muxer;

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_h264_muxer_muxer_1(void)
{
	return &ff_h264_muxer;
}
