/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/rv10-decoder.
 *
 * RV10 decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_rv10_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_rv10_decoder_codec_1(void)
{
	return &ff_rv10_decoder;
}
