/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/rawvideo-demuxer.
 *
 * RAWVIDEO demuxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_rawvideo_demuxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_rawvideo_demuxer_demuxer_1(void)
{
	return &ff_rawvideo_demuxer;
}
