/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/msmpeg4v3-decoder.
 *
 * MSMPEG4V3 decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_msmpeg4v3_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_msmpeg4v3_decoder_codec_1(void)
{
	return &ff_msmpeg4v3_decoder;
}
