/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/codec2raw.
 *
 * CODEC2RAW demuxer, muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_codec2raw_demuxer;
extern const struct AVOutputFormat ff_codec2raw_muxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_codec2raw_demuxer_1(void)
{
	return &ff_codec2raw_demuxer;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_codec2raw_muxer_1(void)
{
	return &ff_codec2raw_muxer;
}
