/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/avs.
 *
 * AVS decoder, demuxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_avs_decoder;
extern const struct AVInputFormat ff_avs_demuxer;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_avs_codec_1(void)
{
	return &ff_avs_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_avs_demuxer_1(void)
{
	return &ff_avs_demuxer;
}
