/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/gif-muxer.
 *
 * GIF muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVOutputFormat ff_gif_muxer;

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_gif_muxer_muxer_1(void)
{
	return &ff_gif_muxer;
}
