/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/pictor-decoder.
 *
 * PICTOR decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_pictor_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pictor_decoder_codec_1(void)
{
	return &ff_pictor_decoder;
}
