/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/mpegvideo.
 *
 * MPEGVIDEO decoder, demuxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_mpegvideo_decoder;
extern const struct AVInputFormat ff_mpegvideo_demuxer;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_mpegvideo_codec_1(void)
{
	return &ff_mpegvideo_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_mpegvideo_demuxer_1(void)
{
	return &ff_mpegvideo_demuxer;
}
