/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/v210.
 *
 * V210 decoder, encoder, demuxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_v210_decoder;
extern const struct AVInputFormat ff_v210_demuxer;
extern const struct FFCodec ff_v210_encoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_v210_codec_1(void)
{
	return &ff_v210_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_v210_demuxer_1(void)
{
	return &ff_v210_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_v210_codec_2(void)
{
	return &ff_v210_encoder;
}
