/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/caf.
 *
 * CAF demuxer, muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_caf_demuxer;
extern const struct AVOutputFormat ff_caf_muxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_caf_demuxer_1(void)
{
	return &ff_caf_demuxer;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_caf_muxer_1(void)
{
	return &ff_caf_muxer;
}
