/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/interplay-dpcm-decoder.
 *
 * INTERPLAY DPCM decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_interplay_dpcm_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_interplay_dpcm_decoder_codec_1(void)
{
	return &ff_interplay_dpcm_decoder;
}
