/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/tscc2.
 *
 * TSCC2 decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_tscc2_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_tscc2_codec_1(void)
{
	return &ff_tscc2_decoder;
}
