/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/mts2-decoder.
 *
 * MTS2 decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_mts2_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_mts2_decoder_codec_1(void)
{
	return &ff_mts2_decoder;
}
