/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/scc-muxer.
 *
 * SCC muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVOutputFormat ff_scc_muxer;

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_scc_muxer_muxer_1(void)
{
	return &ff_scc_muxer;
}
