/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/a64multi-encoder.
 *
 * A64MULTI encoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_a64multi_encoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_a64multi_encoder_codec_1(void)
{
	return &ff_a64multi_encoder;
}
