/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/s302m-encoder.
 *
 * S302M encoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_s302m_encoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_s302m_encoder_codec_1(void)
{
	return &ff_s302m_encoder;
}
