/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/fits.
 *
 * FITS decoder, encoder, demuxer, muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_fits_decoder;
extern const struct AVInputFormat ff_fits_demuxer;
extern const struct FFCodec ff_fits_encoder;
extern const struct AVOutputFormat ff_fits_muxer;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_fits_codec_1(void)
{
	return &ff_fits_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_fits_demuxer_1(void)
{
	return &ff_fits_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_fits_codec_2(void)
{
	return &ff_fits_encoder;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_fits_muxer_1(void)
{
	return &ff_fits_muxer;
}
