/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/jpeg.
 *
 * JPEG family (4 decoders, 4 encoders, 2 demuxers, 1 muxer).
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_jpeg2000_decoder;
extern const struct FFCodec ff_jpeg2000_encoder;
extern const struct FFCodec ff_jpegls_decoder;
extern const struct FFCodec ff_jpegls_encoder;
extern const struct FFCodec ff_ljpeg_encoder;
extern const struct AVInputFormat ff_mjpeg_2000_demuxer;
extern const struct FFCodec ff_mjpeg_decoder;
extern const struct AVInputFormat ff_mjpeg_demuxer;
extern const struct FFCodec ff_mjpeg_encoder;
extern const struct AVOutputFormat ff_mjpeg_muxer;
extern const struct FFCodec ff_mjpegb_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_jpeg_codec_1(void)
{
	return &ff_jpeg2000_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_jpeg_codec_2(void)
{
	return &ff_jpeg2000_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_jpeg_codec_3(void)
{
	return &ff_jpegls_decoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_jpeg_codec_4(void)
{
	return &ff_jpegls_encoder;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_jpeg_codec_5(void)
{
	return &ff_ljpeg_encoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_jpeg_demuxer_1(void)
{
	return &ff_mjpeg_2000_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_jpeg_codec_6(void)
{
	return &ff_mjpeg_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_jpeg_demuxer_2(void)
{
	return &ff_mjpeg_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_jpeg_codec_7(void)
{
	return &ff_mjpeg_encoder;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_jpeg_muxer_1(void)
{
	return &ff_mjpeg_muxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_jpeg_codec_8(void)
{
	return &ff_mjpegb_decoder;
}
