/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/nuv.
 *
 * NUV decoder, demuxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_nuv_decoder;
extern const struct AVInputFormat ff_nuv_demuxer;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_nuv_codec_1(void)
{
	return &ff_nuv_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_nuv_demuxer_1(void)
{
	return &ff_nuv_demuxer;
}
