/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/dnxhd.
 *
 * DNXHD decoder, encoder, demuxer, muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_dnxhd_decoder;
extern const struct AVInputFormat ff_dnxhd_demuxer;
extern const struct FFCodec ff_dnxhd_encoder;
extern const struct AVOutputFormat ff_dnxhd_muxer;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_dnxhd_codec_1(void)
{
	return &ff_dnxhd_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_dnxhd_demuxer_1(void)
{
	return &ff_dnxhd_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_dnxhd_codec_2(void)
{
	return &ff_dnxhd_encoder;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_dnxhd_muxer_1(void)
{
	return &ff_dnxhd_muxer;
}
