/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/pcm-s8-decoder.
 *
 * PCM S8 decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_pcm_s8_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_pcm_s8_decoder_codec_1(void)
{
	return &ff_pcm_s8_decoder;
}
