/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/ico.
 *
 * ICO demuxer, muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_ico_demuxer;
extern const struct AVOutputFormat ff_ico_muxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_ico_demuxer_1(void)
{
	return &ff_ico_demuxer;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_ico_muxer_1(void)
{
	return &ff_ico_muxer;
}
