/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/mv30-decoder.
 *
 * MV30 decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_mv30_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_mv30_decoder_codec_1(void)
{
	return &ff_mv30_decoder;
}
