/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/dsicin-demuxer.
 *
 * DSICIN demuxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_dsicin_demuxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_dsicin_demuxer_demuxer_1(void)
{
	return &ff_dsicin_demuxer;
}
