/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/flac.
 *
 * FLAC decoder, encoder, demuxer, muxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_flac_decoder;
extern const struct AVInputFormat ff_flac_demuxer;
extern const struct FFCodec ff_flac_encoder;
extern const struct AVOutputFormat ff_flac_muxer;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_flac_codec_1(void)
{
	return &ff_flac_decoder;
}

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_flac_demuxer_1(void)
{
	return &ff_flac_demuxer;
}

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_flac_codec_2(void)
{
	return &ff_flac_encoder;
}

__attribute__((visibility("default")))
const struct AVOutputFormat *ffmpeg_ext_flac_muxer_1(void)
{
	return &ff_flac_muxer;
}
