/*
 * Build-time shim for the flac extension.
 *
 * `-include`d before any FFmpeg source compiles. We:
 *
 *   1. Pull in upstream's `config.h` + `config_components.h`
 *      so all the HAVE_X / ARCH_X / CONFIG_X defines exist.
 *
 *   2. `#undef` + `#define CONFIG_X 1` for every flag this
 *      extension needs active. C preprocessing rule: last
 *      define wins, so our overrides take effect for all
 *      subsequent source compiles.
 *
 * Without step 2, FFmpeg's per-codec source files DCE their
 * own decode/encode paths because the base build set every
 * `CONFIG_X` to 0.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand.
 */
#ifndef TTN_EXT_FLAC_SHIM_H
#define TTN_EXT_FLAC_SHIM_H

#include "config.h"
#include "config_components.h"

#undef CONFIG_FLACDSP
#define CONFIG_FLACDSP 1
#undef CONFIG_FLAC_DECODER
#define CONFIG_FLAC_DECODER 1
#undef CONFIG_FLAC_DEMUXER
#define CONFIG_FLAC_DEMUXER 1
#undef CONFIG_FLAC_ENCODER
#define CONFIG_FLAC_ENCODER 1
#undef CONFIG_FLAC_MUXER
#define CONFIG_FLAC_MUXER 1
#undef CONFIG_FLAC_PARSER
#define CONFIG_FLAC_PARSER 1
#undef CONFIG_LPC
#define CONFIG_LPC 1

#endif
