/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/sp5x.
 *
 * SP5X decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_sp5x_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_sp5x_codec_1(void)
{
	return &ff_sp5x_decoder;
}
