/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/roq-decoder.
 *
 * ROQ decoder.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct FFCodec ff_roq_decoder;

__attribute__((visibility("default")))
const struct FFCodec *ffmpeg_ext_roq_decoder_codec_1(void)
{
	return &ff_roq_decoder;
}
