/**
 * Extension init for @tootallnate/ffmpeg-wasm/extensions/pcm-s8-demuxer.
 *
 * PCM S8 demuxer.
 *
 * AUTOGENERATED by scripts/gen/. Do not edit by hand — re-run
 * the generator after changing the upstream FFmpeg checkout.
 */

#include <stddef.h>

extern const struct AVInputFormat ff_pcm_s8_demuxer;

__attribute__((visibility("default")))
const struct AVInputFormat *ffmpeg_ext_pcm_s8_demuxer_demuxer_1(void)
{
	return &ff_pcm_s8_demuxer;
}
